### ISSUE TITLE
Remove web source icon

### ISSUE THREAD

**Issue by mhdhejazi** [mangerlahn/Latest#103]
The icon for AppStore is very useful, but the other icon is confusing. It gives the impression that this is a *new* item (what does this mean?), and has nothing to do with the web.

I guess the other icon can be safely removed. It's not really needed as people use Latest to update the apps downloaded from the web. The exception here is the AppStore apps which have their proper icon now.

Removing the other icon also simplifies the UI a little bit.

**Comment by WorkInProgress-Development** [comment]
The other icon is to represent the Sparkle Project (https://github.com/sparkle-project/Sparkle), which is a program which many pieces of software downloaded 'from the web,' as you said, use to update. I find it is an effective way to differentiate between app store and sparkle versions of the same software for myself.

It would be ideal to keep it in, especially if the application expands to other update methods, such as discussed in #45, #8, and #92

I do see how it might be confused with a 'new!' icon, so possibly there could be a preference to disable those icons.

**Comment by mangerlahn** [comment]
You are right, this icon represents the Sparkle source. I just did not want to use the term "Sparkle" just yet, in hope I come up with a better name when other sources are added. 

I will probably move these icons into the detail view, where it is less prominent. I have received multiple complaints on the way that this is currently presented..

**Comment by mangerlahn** [comment]
Fixed in 38aeb7d
