### ISSUE TITLE
update issues

### ISSUE THREAD

**Issue by fabfrodo** [mangerlahn/Latest#111]
Hi, thank you for this App!

I've found 2 issues
1. latest is showing me an update for [Subtrack](https://apps.apple.com/de/app/subtrack-track-subscriptions/id1519946553) 1.1.1 - but the App Store still offers 1.1; hence no update is available
2. popular updates like google Chrome or Amazon Photos are not displayed s

**Comment by mangerlahn** [comment]
Hi!

There is currently an issue with App Store checking for apps that are available for macOS and iOS. Subtrack is on v1.1.1 on iOS, v1.1 on macOS. Apple currently reports the iOS version number even if I ask for the Mac version number. There is probably nothing we can do until Apple fixes this on their side. More details here: #106 

For other apps: There are many update mechanisms out there, some apps built entirely custom ones. I hope to bring support to more apps, but I can't guarantee anything on that front, especially for apps that have their own updater, like Chrome. See #19 for more details.
