### ISSUE TITLE
Latest's own download URL redirected to insecure HTTP

### ISSUE THREAD

**Issue by vszakats** [mangerlahn/Latest#112]
```
$ curl --disable --verbose https://max.codes/latest/download
[...]
< location: http://max.codes/latest/Latest.zip
[...]
```

Notice that HTTPS is replaced with HTTP in the redirect, meaning that the app will be downloaded via insecure channel. `brew install --cask latest` is also affected since it uses this particular URL for downloads/updates.

**Comment by mangerlahn** [comment]
Ouch, thank you for pointing that out! I fixed it immediately :)
