### ISSUE TITLE
Misidentifying an update

### ISSUE THREAD

**Issue by hasantahir** [mangerlahn/Latest#118]
Hi,

First thanks for the awesome package that is indeed a great time saver. In some instances, however, the app wrongly identifies an update:

![image](https://user-images.githubusercontent.com/11236148/110830189-d8416d00-8290-11eb-9e7e-04a7110ec7ae.png)

In the image, both versions are in fact the same for the app, `GeoGebra Classic 6`. Rather than checking the whole string, would it be useful to just compare first the patch, then minor and then major version numbers?

**Comment by shepazon** [comment]
This is also prone to finding the iOS version of an application instead of the native version, now that compatible iOS apps are listed in the Mac App Store for use on M1 machines. This happens with Graphic from Picta, for one.

**Comment by RicardoVelaC** [comment]
Another one here

- Everyday Habit Tracker

<img width="1013" alt="Latest" src="https://user-images.githubusercontent.com/6016812/120111806-a941e580-c173-11eb-8580-3ec960a3ff18.png">

**Comment by mangerlahn** [comment]
Thanks for the reports! I hope this is resolved with the 0.9 update, if you still see issues, please open a new issue :)
