### ISSUE TITLE
Make the app installation process easier on macOS

### ISSUE THREAD

**Issue by rakleed** [mangerlahn/Latest#121]
Please make the process of installing the app on macOS more convenient either by making a DMG installer with the Applications folder and the app itself or immediately after launching, prompt the user to move the app to the Applications folder (if you determine that the app is not launched from the Applications folder).

**Comment by mangerlahn** [comment]
Thanks for writing that down! :)

**Comment by methbkts** [comment]
I suggest the use of https://github.com/sindresorhus/create-dmg for making the DMG easily

**Comment by mangerlahn** [comment]
Fixed with v0.10
