### ISSUE TITLE
iOS version detected instead of macOS

### ISSUE THREAD

**Issue by nrlquaker** [mangerlahn/Latest#122]
Latest detects iOS version of the app, not the macOS one.

<img width="1013" alt="Screenshot 2021-05-05 at 20 43 58" src="https://user-images.githubusercontent.com/2573638/117185639-ba047300-ade2-11eb-9aca-7f27186ecfd5.png">

<img width="1532" alt="Screenshot 2021-05-05 at 20 45 20" src="https://user-images.githubusercontent.com/2573638/117185730-d1436080-ade2-11eb-9d1a-8b1f091bb0c1.png">

**Comment by mangerlahn** [comment]
Yes, this an issue that we can't do much about, as Apple returns iOS app updates for certain macOS apps. I should probably disable update checks for affected apps to avoid false updates. As this is a duplicate of #106, I am closing this for now, but please don't hesitate to post further comments or suggestions :)
