### ISSUE TITLE
Crash due to unavailable attribute combination in update notes

### ISSUE THREAD

**Issue by sleifer** [mangerlahn/Latest#124]
In Version 0.7.3 (462), trying to view the notes for the update from 28 to 29 of Reveal (https://revealapp.com) crashes Latest.

I forked the project and recreated the crash under debugger and found it to be in the format method of ReleaseNotesTextViewController when copying attributes across to the font used for display.

I was able to prevent the crash by guarding the output of creating the new NSFont object.

I'm happy to create a pull request if you like.

**Comment by mangerlahn** [comment]
Hi,

Sorry for my slow response. The crash *should* be the same as #125, which has already been fixed. I just did not get around to releasing the fix, but there is hope for the coming weeks 😅

Could you try the current develop branch and check whether the crash still occurs, if it hasn't fixed itself by now 🙃

**Comment by sleifer** [comment]
Running against develop (97e21be) I no longer see a crash when viewing release notes for a Reveal update (30 to 31 in this case) whereas this update does cause a crash on the current public release. That's great.

**Comment by mangerlahn** [comment]
Awesome, thanks for testing! I'll try to put an update out soon! 😅
