### ISSUE TITLE
Intermittent error on Mac OS Big Sur - Latest shows a 'spinner' trying to load the list of applications and current status

### ISSUE THREAD

**Issue by thecronester** [mangerlahn/Latest#126]
Intermittent error on Mac OS Big Sur 11.5.1; MacBook Pro (15-inch, 2017); 2.9 GHz Quad-Core Intel Core i7; 6 GB 2133 MHz LPDDR3; 500GB SSD.

This has happened twice: open Latest and it just shows a 'spinner' trying to load the list of applications and current status. 
Not sure how it resolves but it seems to eventually - some days later - fix itself. 
I have also tried a full uninstall / reinstall of the latest Latest release but it seemed to make no difference. 

Looking in Mac OS Console at system.log etc. I can't see anything untoward being reported by Latest or while Latest is running.

**Comment by thecronester** [comment]
As happened previously when this occurred, some days have passed and each day I saw the spinner but this morning I opened Latest and the list of Apps appeared as normal. It's been about 7 days. 
Would definitely say there's some strange local data state or network issue happening? 
My other Mac (a Mac Mini M1 2021 on same OS level and same version of Latest) has not exhibited this spinner behaviour.

**Comment by mangerlahn** [comment]
Hi, thanks for the report! The list of installed apps is currently being fetched using Spotlight. This technique is fast but seems to be unreliable sometimes. I plan to implement a fallback, as noted in #96 :)

**Comment by thecronester** [comment]
Hi Max. Thanks for the update. Makes sense. It's definitely intermittent and I've only seen it on my MacBook Pro and I think it seems to occur just after a Mac OS update but as mentioned in my Issue report then resolves of itself, no other intervention by me, after some days.

**Comment by mangerlahn** [comment]
Ok great, I'll be closing this as a duplicate then 😊
