### ISSUE TITLE
Not detecting apps installed via brew

### ISSUE THREAD

**Issue by rbadapanda** [mangerlahn/Latest#127]
I don't see dropbox app in the list of 'installed apps' in side the Latest app.

Dropbox is already installed to my /applications folder via brew cask.

Is there a plan to support this scenario in future ? or if I am missing something, Please share how to use and clsoe this ticket.

**Comment by mangerlahn** [comment]
Hi, thanks for the report!
I plan to add support for Brew in an upcoming update. I documented this in #45, would it be ok for you if I close this one as a duplicate?
