### ISSUE TITLE
Wrongly reporting updates for iOS and not macOS......

### ISSUE THREAD

**Issue by wilky761** [mangerlahn/Latest#128]
Hi there,

I really like this really useful app, however, this app is wrongly reporting updates for iOS, and not macOS.

As an example:

Health Auto Export - I have the latest macOS app installed (v2.02.) but your app is telling me that v5.1.2 is the latest. v5.1.2 is the iOS app.

Same for the "Units" app......

Any way to fix this, other than "ignoring" the update, which I assume will only apply until the next version update is available?

**Comment by core-code** [comment]
this is one of many glaring bugs in Apple's MAS API. we've sent a bug-report but Apple doesn't care.
