### ISSUE TITLE
Updateable apps list (left panel) empty on 0.8

### ISSUE THREAD

**Issue by luckman212** [mangerlahn/Latest#130]
Thanks @mangerlahn for the new release!

When I ran it though, it said "3 updates available" in the toolbar area, however the left panel was empty. Clicking the small (i) button launched the AppStore and took me to the first app that needed updating. So in this way, I was able to update them one by one. But something seems off.

I tried deleting the prefs plist but that didn't help. M1 Mac Mini on Monterey 12.2.1.

(sorry I wasn't able to capture a screenshot...)

**Comment by mangerlahn** [comment]
Wow, thanks for the quick report! Guess I was too excited to finally get an update out of the door. This is fixed in a new build of 0.8.

**Comment by luckman212** [comment]
The fix was even quicker than the report! 

Confirmed, working great now — thanks 👍 

![image](https://user-images.githubusercontent.com/1992842/158029208-89ae3f45-1608-49d1-aad8-ffabf0e150ca.png)
