### ISSUE TITLE
Missing updates for Subler 

### ISSUE THREAD

**Issue by foss-** [mangerlahn/Latest#131]
Latest: 0.8
macOS 12.2.1

Update from 1.7.2 to 1.7.3 not showing up in Latest. Subler is [using Sparkle](https://bitbucket.org/galad87/subler/issues/177/create-new-version-with-latest-sparkle-and) so as per https://github.com/mangerlahn/Latest/issues/9 would expect to see and execute the update in Latest.

**Comment by mangerlahn** [comment]
Thank you for reporting this! I found a bug in the code that goes through the sparkle feed.
