### ISSUE TITLE
Non-commercial does not qualify as open source

### ISSUE THREAD

**Issue by comradekingu** [mangerlahn/Latest#134]
The NC clause is a restriction on use. This is not allowed, so it becomes a trademark violation to call it open source.
I suggest asking current contributors to relicense, so it can be removed.

**Comment by mangerlahn** [comment]
Thank you for bringing that to my attention! I am not sure why I chose CC back then. I decided to go with GPL and will change the license once the last contributor agreed.

**Comment by mangerlahn** [comment]
Fixed with 882b98bdb512ea39d58d61d1e5f218e3398a4efb. 

From Latest v0.9 going forward, the app will be licensed under GPL.
