### ISSUE TITLE
Update-checking Latest installed in /Applications folder produces an error

### ISSUE THREAD

**Issue by Gummibando** [mangerlahn/Latest#14]
When trying to update-check Latest itself (Application menu > Check for Updates…) installed in the /Applications folder, it shows an error saying it can't be updated from a read-only location.
If Latest is started from basically any other location, like ~/Applications, the update check works.

<img width="420" alt="screen shot 2018-05-28 at 23 35 28" src="https://user-images.githubusercontent.com/34392542/40630213-fb475fe0-62d0-11e8-9f36-acd20f5a4762.png">

**Comment by mangerlahn** [comment]
Thats weird.

**Comment by Gummibando** [comment]
Ach ne, aus Leipzig :)

Are you able to reproduce it? I can update-check it when started from Desktop, from ~/Applications, even from the Downloads folder (which actually **should** be a read-only location). Just not from the /Applications folder.

**Comment by mangerlahn** [comment]
Grüße :)

**Comment by Gummibando** [comment]
Yep, removing the quarantine xattr did the trick.
