### ISSUE TITLE
Allow release notes of all installed apps

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#15]
I keep a pretty up-to-date system and only had two apps needing updates when I first opened Latest. What I would have loved is the ability to quickly see release notes from up-to-date apps.

**Comment by mangerlahn** [comment]
Thanks for writing! So basically the idea of the App Stores, where you can see past updates and their release notes?

**Comment by Wdavery** [comment]
Exactly! I think that would add a lot of value to the app, and make it useful even when there are no updates

**Comment by mangerlahn** [comment]
Completed with 66f58b129f2da9db617cf2137dee10830e7014cb
