### ISSUE TITLE
Ignore certain Apps

### ISSUE THREAD

**Issue by jvimedia** [mangerlahn/Latest#17]
Well, have a ignore list for certain .app's 
- useful for developers/ if you run different versions of a app for whatever reason ... and don't want to trigger the update for it)

**Comment by mangerlahn** [comment]
Good point, thanks!

**Comment by Wdavery** [comment]
Definitely would love to see this as a feature. I'm running a few older versions of apps that I do not want to update, it'd be great to right click and have an option to hide/ignore. 

Maybe you could add a third section to the list?
- Available Updates
- Ignored Updates
- Installed Updates

**Comment by mangerlahn** [comment]
I like the idea of having ignored updates within the list itself. Probably with a toggle similar to installed updates. Should not be too hard to do 😊

**Comment by mangerlahn** [comment]
Fixed with e3bee60e11eaf0d30c68ad9656f6ddb0814be344
