### ISSUE TITLE
Crash when refreshing after deleting an app with a pending update

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#176]
1. have an out-of-date app
2. scan for updates in Latest
3. delete the app through finder
4. refresh in Latest

## Expected

- pending update should disappear from sidebar

## Actual

- crash

## Crash report
- [Latest-2022-06-09-132536.ips.zip](https://github.com/mangerlahn/Latest/files/8870267/Latest-2022-06-09-132536.ips.zip)

**Comment by mangerlahn** [comment]
Thanks for the report! Can you reproduce this with 0.8.1?

**Comment by mangerlahn** [comment]
Thanks for the quick update!

I still quite don't understand what is going on. Once I remove an app from the Applications folder, it gets removed pretty much immediately within Latest. I am not fast enough to reload within Latest. 

Do you mean removing the app while it is updating though Sparkle? I was not able to make it crash there either.

**Comment by gingerbeardman** [comment]
I can't remember. But I'll keep an eye out!

**Comment by gingerbeardman** [comment]
Just got one on the latest version.

Could it be when I request an update twice on an app? (I'm impatient)

**Comment by gingerbeardman** [comment]
Crash report [Latest-2022-11-22-222634.ips.zip](https://github.com/mangerlahn/Latest/files/10071636/Latest-2022-11-22-222634.ips.zip)

**Comment by gingerbeardman** [comment]
Any ETA on 0.10?
