### ISSUE TITLE
latest didn't find any updates

### ISSUE THREAD

**Issue by pthoelken** [mangerlahn/Latest#192]
After installing with brew (and also manually) the app doesn't find any updates. Did I miss some configurations in latest App? 
![image](https://user-images.githubusercontent.com/12643853/182090282-3c34313d-586a-4793-b31c-36886ea479cf.png)

But another software can find some updates about my applications.
![image](https://user-images.githubusercontent.com/12643853/182090733-4e20f8f5-24b3-46cf-895e-b9a5ec538a14.png)

Maybe the problem is our company proxy server? Do you have any proxy server configuration?

**Comment by mangerlahn** [comment]
Sorry for the late reply. The other app you are mentioning is using a different approach for update checks and is able to check more apps for updates. There are plans to improve this for Latest :)
