### ISSUE TITLE
Alpha release of Lunar showing as available update to stable channel

### ISSUE THREAD

**Issue by NilsEnevoldsen** [mangerlahn/Latest#194]
Latest reports that Lunar 5.7.4a2 is available:

<img width="823" alt="latest" src="https://user-images.githubusercontent.com/222743/184186538-09ff840c-81bf-40f4-a4d1-76eedd3cc339.png">

But Lunar itself reports that I am up to date with 5.7.3:

<img width="372" alt="lunar" src="https://user-images.githubusercontent.com/222743/184186571-78ef2f78-a9f4-4ba7-86f7-862b9967ab88.png">

Since I'm unsure if this is an issue with Latest or Lunar, I'm reporting to both projects: https://github.com/alin23/Lunar/issues/479#issue-1336218702

**Comment by alin23** [comment]
Right now **Latest** is working correctly, the alpha updates are valid but restricted to users that opt in to the alpha channel:

![alpha update channel](https://files.lunar.fyi/update-channel.png)

If @mangerlahn is also doing app-specific setups, then for Lunar there's a stable only appcast here which is also used by `brew --cask`: https://files.lunar.fyi/appcast-stable.xml

If only `Info.plist` extraction is used then there's nothing to be done, **Latest** is working as expected.

**Comment by mangerlahn** [comment]
Thanks for clarifying :)

**Comment by alexreg** [comment]
I'm on Release channel but still getting offered alpha updates, I'm afraid.

<img width="369" alt="Screenshot 2022-12-13 at 15 55 07" src="https://user-images.githubusercontent.com/67036/207381433-36154467-209d-4d1b-bfe6-02b24fd73f6e.png">

<img width="1072" alt="Screenshot 2022-12-13 at 15 57 15" src="https://user-images.githubusercontent.com/67036/207381756-b57b1527-b3cf-45a0-9743-bfc402b16c2e.png">

**Comment by NilsEnevoldsen** [comment]
> @mangerlahn I'm on Release channel but still getting offered alpha updates, I'm afraid.

Me too. The determination above is that this is expected behavior, unfortunately.

**Comment by alexreg** [comment]
@NilsEnevoldsen Yes... I reread, and it seems you're right. However, I would consider this more a flaw/naivety of Latest's update-checking mechanism. It would make most sense to modify its behaviour here.
