### ISSUE TITLE
Crash when updating apps having marked some as ignore

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#203]
1. start update of some apps
2. (whilst they are updating) ignore some other apps
3. latest will eventually crash

Perhaps related to #176

Crash log
[Latest-2022-09-07-151200.ips.zip](https://github.com/mangerlahn/Latest/files/9506930/Latest-2022-09-07-151200.ips.zip)

**Comment by mangerlahn** [comment]
Oops, looks like one can have too many simultaneous update operations 😅
I'll make sure to reduce the amount of simultaneous checks. Not sure if that fixes the other crashes you experienced though. Thanks for reporting! :)

**Comment by gingerbeardman** [comment]
Any chance of a new release with the latest fixes?

**Comment by mangerlahn** [comment]
Hope to find some time this weekend :)
