### ISSUE TITLE
Ukrainian localisation

### ISSUE THREAD

**Issue by andryua** [mangerlahn/Latest#205]
Hi!
Can You add Ukrainian localization? I can help you with that.
Thanks!

**Comment by mangerlahn** [comment]
I am happy to add Ukrainian! :) 
You can help by adding translations here: 
https://hosted.weblate.org/languages/uk/latest/

Once this is done, I can add it into the app. Stay safe!

**Comment by mangerlahn** [comment]
8960bf9ea23303eb09c3e9b17f5125d0a56ba0fe The localization is now there, will ship with the next update :)
