### ISSUE TITLE
Menu Bar app

### ISSUE THREAD

**Issue by kyellareddy** [mangerlahn/Latest#213]
What do you think about adding a menu bar app that would show a notification icon when there was an upcoming update?

**Comment by mangerlahn** [comment]
I have planned to add a background mode for latest (described in #53). That way, notifications could be shown once updates become available. I also thought about building a widget that could show available updates.

Not sure about a menu bar icon though. I feel like that menu bar is always so crowded 😅. Would it just show the number of available updates? What would you like to happen when it gets clicked? Open the main window, or should it have a different UI?

**Comment by JonoHaysom** [comment]
Id love to have a menubar indicator where the app has a small number next to its logo for the number of apps needing to be updated from the background task

**Comment by mangerlahn** [comment]
Dupe of #64
