### ISSUE TITLE
Show Unsupported Apps Should Be Independent of "Show Installed Apps"

### ISSUE THREAD

**Issue by Stickyhavr** [mangerlahn/Latest#214]
Hello. New user here—loving your app so far. Just wanted to make a quick suggestion: it seems like the ignored apps and the unsupported apps are tied to the "show installed apps" option under view. 

It seems to me like it would be helpful to be able to see unsupported apps (greyed out, like they usually are) without seeing all the other installed apps. So, for example, any apps that have updates would be at the top, and any apps that Latest doesn't support could be underneath and greyed out. That way we have a quick list of apps that we need to be updating manually ourselves and we'll know that latest is updating all the rest.

Does that make sense? Or am I using it wrong?
Thanks!

**Comment by mangerlahn** [comment]
Good point, should be easy to do :)

**Comment by mangerlahn** [comment]
Fixed with d09da48b41864faa5f8cd95f54c6c4a6d5128e52
