### ISSUE TITLE
The app can't scan all the installed apps

### ISSUE THREAD

**Issue by powersagitar** [mangerlahn/Latest#217]
I'll take myself as an example. I have over 90 apps installed on my mac, but *Latest* can only find 25 of them. Could you please add support for all the apps?

**Comment by mangerlahn** [comment]
Thanks for writing! I plan to support more sources, but I probably won't start adding support for individual apps. Please refer to this for further information: https://github.com/mangerlahn/Latest/issues/19#issuecomment-397802484
