### ISSUE TITLE
Tast false update info

### ISSUE THREAD

**Issue by PLSomebody** [mangerlahn/Latest#218]
Latest shows that I have Toast 20 Titanium.app version "20.1 (7206) 20.1" and it informs that update "20.1 (7206) (7206)" is available. The problem is that both are the same version of Toast. I remember that in the past Latest had similar problems with previous Toast versions too. Maybe it will be possible to maintain this problem in future updates.

**Comment by mangerlahn** [comment]
Thanks for the report! I hope this is resolved with the 0.9 update, if you still see issues, please open a new report.
