### ISSUE TITLE
App crash in the last version 0.8.3

### ISSUE THREAD

**Issue by SMH642800** [mangerlahn/Latest#226]
When I open the app, and it crashed.
And I check the crash report about 10 times, it always says that "Crashed Thread:  Dispatch queue: DataStoreQueue"

Macos : 12.6.1
Latest version : 0.8.3

Crash reports (I took the last three records) : 
[Latest-2022-12-11-105146.ips.zip](https://github.com/mangerlahn/Latest/files/10201403/Latest-2022-12-11-105146.ips.zip)
[Latest-2022-12-11-105031.ips.zip](https://github.com/mangerlahn/Latest/files/10201404/Latest-2022-12-11-105031.ips.zip)
[Latest-2022-12-11-104711.ips.zip](https://github.com/mangerlahn/Latest/files/10201405/Latest-2022-12-11-104711.ips.zip)

**Comment by adamlogan** [comment]
I'm getting this issue too installing for the first time. Seems like it always crashes just as it completes scanning apps.

On a side note, I was having trouble extracting the app with BetterZip. I had to extract with stock Archive Utility.

This on 2021 14" M1 Pro w/ MacOS Ventura 13.1

**Comment by SMH642800** [comment]
Update : 

After I upgraded my macOS version to 13.1, latest app not crashed anymore.

I don't know why. Same app list, same setting, it just work after upgraded.

**Comment by qlife1146** [comment]
I have the same issue. Is there a solution? I updated it to 13.1 because it didn't work in 13.0.1 version, but it still doesn't run and crashes.

**Comment by mangerlahn** [comment]
Thank you all very much for reporting! I was able to locate the source of the crash and fixed it. I hope this will resolve the issues for you once an update is out.
