### ISSUE TITLE
VST Plugins

### ISSUE THREAD

**Issue by gabriel-bortolatto** [mangerlahn/Latest#230]
Man, your app is convenient, geez. Thank you.
It doesn't make you money, though.
Now...
You manage to do the same update management for VST plugins millions of musicians and audio engineers are using every day, you're a millionaire. Promise.

Just search YouTube, audio plugins is a ginormous topic right now, especially because now the music world is going indie, and everyone is producing their songs at home. For real, millions and millions of people. And now collecting plugins is just as big of a craze as tech reviews are. So any plugin review on YouTube just blows up. People buy loads of them, from different manufacturers.

And some manufacturers have their app, to install and update plugins. Most don't. And for users, it's a huge mess.
In the music scene, not up-to-date plugins simply affect your work, period. 

So this is a tip.

Charge a buck for this, you'll conquer the world.

The guys from OwlPlug tried doing this, but they... they just...
They're just not the ones to do it, you know?...

https://github.com/DropSnorz/OwlPlug/releases

They tried creating a multiple-manufacturer plugin manager, with uninstall and update. 
But man... you gotta make it right. Just like your app.
Simple, and right.

The one who does this first, will dominate this market, wich is growing like crazy. This is a necessity.
Mark my words.

(I will partner you, if you trust this tip)

**Comment by mangerlahn** [comment]
Thank you for reaching out! Latest is an app I build in my free time, without any commercial interest. It feels like this plugin support is a bit out of scope for what this app currently is, and seems unfeasible given the little amount of time I can pour into maintaining the project. 
But since it is open source, you could just take the code and run with it, if you see fit :)
