### ISSUE TITLE
Filter updates that are not compatible with OS

### ISSUE THREAD

**Issue by bdougherty** [mangerlahn/Latest#241]
Latest is showing a Mac App Store update for me for Dato version 4.4.0 which requires Mac OS 13, but I am on Mac OS 12. I'm not sure if this is an issue with apps outside the store.

**Comment by mangerlahn** [comment]
Had that planned for the next update, thank you for writing it down! :)

**Comment by mangerlahn** [comment]
Resolved with 1d8635b
