### ISSUE TITLE
incorrect versions of apps being marked as latest?

### ISSUE THREAD

**Issue by patdiddy** [mangerlahn/Latest#242]
When I go to run a check of latest, two apps in my list were asking to be updated to a previous version. Smart Converter Pro 3 said that the latest version is 2.0.1, but the newest version I have is 3.1.2.1, and Virtual DJ (which comes from the App Store) says the latest version is 2021 b7166 when it is actually 8.5.7166. Please fix this.

**Comment by mangerlahn** [comment]
Thanks for the report! I hope this is resolved with the 0.9 update, if you still see issues, please open a new report.
