### ISSUE TITLE
Beta versions incorrectly reported as latest

### ISSUE THREAD

**Issue by rrva** [mangerlahn/Latest#243]
BetterDisplay https://github.com/waydabber/BetterDisplay/releases has a beta version out that is incorrectly marked as a possible upgrade. 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/887132/216825599-2089e238-eaed-4ce6-b501-b1b1df0dad97.png">
Listing beta versions should be optional and default off

**Comment by mangerlahn** [comment]
Thanks for reporting! I believe this should be fixed with changes I made in the upcoming update. If you still see this issue after updating Latest, please report!
