### ISSUE TITLE
Include Homebrew updates

### ISSUE THREAD

**Issue by mpwg** [mangerlahn/Latest#262]
i have several [Homebrew](https://brew.sh) stuff installed.

It would be nice if Latest could:
1. List all Homebrew updates
2. offer to install them as well

**Comment by mangerlahn** [comment]
I have a prototype laying around for over half a year now on my machine, just need some time to actually finish this 😅

**Comment by mangerlahn** [comment]
This appears to be a duplicate of #45. I would focus on casks at the moment, since Latest is a very UI-centric app.
