### ISSUE TITLE
updating apps with Latest leads to damaged file-modification and file-creation dates

### ISSUE THREAD

**Issue by core-code** [mangerlahn/Latest#263]
summary:
nearly all "file creation dates" are wrong and many "file modification dates" are wrong after updating apps with Latest

steps to reproduce:
1.) download an old version of an app that can be updated by Latest. e.g. https://su.airbuddy.app/kCRSAmcjBc/AirBuddy_v2.6.3-602.dmg
2.) update the app using Latest
3.) download a fresh copy of the app for comparison, e.g. https://su.airbuddy.app/kCRSAmcjBc/AirBuddy_v2.7-628.dmg
4.) check the file dates of the copy that has been updated by Latest and the file dates of the original download, e.g. 

```ls -laR /Applications/AirBuddy.app```
```ls -laR /Volumes/AirBuddy_v2.7-628/AirBuddy.app```

5.) compare those dates. they should match, but do not. nearly all "file creation dates" are wrong in the updated-by-latest-copy and many "file modification dates" are wrong in the updated-by-latest-copy. note that ```ls``` can only display the modification dates, the creation dates are available e.g. via ```-[NSURL getResourceValue:&date forKey:NSURLCreationDateKey error:nil]```
 

regression:
• when updating apps using a built-in updater like Sparkle, or using MacUpdater or manually in the Finder then the problem does not occur and the file dates are correct

notes:
• this bug has lead to tens of thousands of damaged app-release-dates in MacUpdater's database. we've been trying to find the culprit here for years. unfortunately we've been looking for bugs in our code, when we should have been looking for bugs in other apps.

**Comment by core-code** [comment]
yes metadata can be unreliable, but better information is available only for codesigned apps.

i'll try to come up with confirmation that this only affects apps with delta-updates

**Comment by mangerlahn** [comment]
Sorry for being late to the topic. As mentioned before, Latest just forwards update requests to the Sparkle framework, so I'm not sure there is something I can do about it. Would be happy to add a fix, if possible. 

Have you any new info on this issue?

**Comment by core-code** [comment]
thanks here

our plan would be to 1.) test if the issue really only applies to apps updated with "delta updates" and if so 2.) submit a patch to sparkle to include file metadata in their delta file format

in any case, if what we currently suspect is true (issue stems from sparkle and not from latest and only applies to delta-updates) then i'd be fine with closing this issue

**Comment by mangerlahn** [comment]
Closing for now, happy to reopen if anything else comes up
