### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by EvanZhouDev** [mangerlahn/Latest#264]
Hello! I am just curious as to how this extension works under the hood... is there a terminal command it is running? Or AppleScripts?

I want this information to make a [Raycast](https://raycast.com) extension for this App. Thank you!

**Comment by mangerlahn** [comment]
From the mail I wrote earlier:
> As you correctly stated, Latest currently supports two kinds of apps, Sparkle and App Store. 
For Sparkle, checks are being done by the Sparkle framework. I used to do this myself by parsing the feed XML, but the apps feeds often slightly differed, so there were quite some bugs with this manual parsing.
>
> 1. For Mac App Store apps I manually compare the version numbers. They are extracted like the Sparkle feed URL from the app bundle’s Info.plist. The relevant keys here are CFBundleVersion and CFBundleShortVersionString. These are compared to the App Store listing of the app, which can be retrieved using the iTunes API. More on this in MacAppStoreUpdateCheckerOperation. Same goes for Catalyst apps, which slightly differ in structure.
>
> 2. Updates for Sparkle-based apps are performed using the Sparkle framework. IIRC the framework then runs a different process that updates the app. It’s a little harder for App Store apps. Latest is calling private frameworks within the OS and asks to perform downloads of apps that should be updated. See MacAppStoreUpdateOperation for more details. This is largely based on the implementation used in mas-cli. You may even be able to call that if it is installed on a users device.
