### ISSUE TITLE
MacOS Version 12.6.8 (21G725) causes "Latest  version Version 0.9 (935)" to not find itslef at boot and provides Finder a  -80 Error message

### ISSUE THREAD

**Issue by donwlarson** [mangerlahn/Latest#269]
FYI,

As of August 30, 2023.

MacOS Version 12.6.8 (21G725) causes "Latest Version 0.9 (935)" to not find itself at boot and provides Finder a  -80 Error message on the Desktop.

Sincerely,

Donald W. Larson
(760) 505-9582
donwlarson@gmail.com

**Comment by mangerlahn** [comment]
Thanks for your report! Did you add Latest to the apps that should launch at boot time?

**Comment by donwlarson** [comment]
Same issue with macOS 12.7 on October 9, 2023.

Don

**Comment by mangerlahn** [comment]
Could you send a screenshot of what error you are seeing? I don't know what's going on here.

**Comment by donwlarson** [comment]
Hi, 

I recently updated macOS to 12.7. I doubled-checked your previous suggestions to verify their settings match.

Today, I rebooted my 2015 iMac running 12.7 and no error message.

Thank you for your app.

Don Larson, San Diego, CA
