### ISSUE TITLE
Certain apps do not display correctly

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#27]
Out of my ~50 apps, two do not display properly.

Monolingual - https://ingmarstein.github.io/Monolingual/
Which shows the name and release notes, but no icon/date/version.

<img width="969" alt="monolingual" src="https://user-images.githubusercontent.com/12989893/44218295-6855bf00-a147-11e8-8280-2e49d34999a2.png">

BBEdit - http://www.barebones.com/products/bbedit/index.html
Which shows no name/notes/icon/date/version.

<img width="969" alt="bbedit" src="https://user-images.githubusercontent.com/12989893/44218294-6855bf00-a147-11e8-817d-9c6c59a00eab.png">

Both display empty "Label" tags, so it may be a problem of those apps not using standard tags.

**Comment by Wdavery** [comment]
If it does turn out to be a 3rd party problem, perhaps there should be a fallback to the name of the .app, because Latest does link correctly to it in finder. 
Then display an error explanation and offer to hide the app from the list.

Would also solve #17

**Comment by mangerlahn** [comment]
Thanks for the detailed error description!

Monolingual stored some version information in an older Sparkle format I was not aware of. That works now correctly. 
BBEdit uses its own format here, so it (and other apps I can't parse) will be ignored at the moment.

There were 3 independent issues here and each fix would have fixed the Monolingual problem. I applied all three fixes an am pretty confident that we will never see a blank row again 😉

**Comment by mangerlahn** [comment]
Fixed with c7792ecb088bf9faf76a2e9935e9d9543bcbaaf4

**Comment by Wdavery** [comment]
I've run into another issue along these lines. 
Simple Screen Shade - which is a MAS app, shows the icon/name correctly but no date/version/notes. 

https://itunes.apple.com/ca/app/simple-screen-shade/id959381052?mt=12
It is a paid app so if there is anything that would help debug this just let me know.
