### ISSUE TITLE
build error: Network/nw_object.h' file not found,  Could not build Objective-C module 'Network'

### ISSUE THREAD

**Issue by GanZhiXiong** [mangerlahn/Latest#280]
- macOS 13.5 (22G74)
- Xcode 15.0.1

My operation steps: 
1. `git clone --recurse-submodules git@github.com:mangerlahn/Latest.git`
2. open Latest.xcodeproj
3. Build and Run

<img width="712" alt="image" src="https://github.com/mangerlahn/Latest/assets/27394631/6e8aa1db-f462-4dca-9824-98406a144d20">

**Comment by mangerlahn** [comment]
Thanks for the report! You are correct, the main branch does not currently build on the latest Xcode. I fixed this on the `develop` branch. If you check that out, you should be able to build the app :)
Does this help?

**Comment by GanZhiXiong** [comment]
Thank you for your reply. Yes, don't have this problem with the develop branch
