### ISSUE TITLE
Update function Open the app in the latest version

### ISSUE THREAD

**Issue by jmcerrejon** [mangerlahn/Latest#287]
_OS: MacOS Sonoma 14.1.1 | ARM M1 Pro_
_App version: 0.10 (1111)_

**Issue**

When I try to update an app, click on the Update button on the right, or the Update option in the context menu. Both actions act to open the app. When I choose open, the app is opened, too. Tried on all the apps I have available to update.

![Screenshot 2023-11-28 at 09 00 55](https://github.com/mangerlahn/Latest/assets/1942431/659f6d2b-92da-4998-a461-6b4d88eb624b)

Thanks for the app! Very useful.

**Comment by madnil** [comment]
_OS: macOS Catlina 10.15.7
App version: 0.10 (1111)_

I can confirm this issue. The list also shows updates for apps which are already the latest version, but show a slightly different version number like "current version 1.10" and "new version 1.10 (build 1103)". Also no release notes are shown for all the listed apps.

**Comment by mangerlahn** [comment]
@madnil that issue is reported in #285, please add all apps that have this issue there

**Comment by jmcerrejon** [comment]
Apologies. We continue on that thread.
