### ISSUE TITLE
Add Search Functionality

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#29]
It'd be useful on larger systems to have a search functionality to quickly find specific apps.

**Comment by mangerlahn** [comment]
Yeah I had the same feeling when I saw the list of all installed apps 😅
<img width="286" alt="screen shot 2018-08-19 at 17 52 58" src="https://user-images.githubusercontent.com/11056766/44310558-c5b46f00-a3d8-11e8-882c-2ec8b582e218.png">

This would probably look like the search bar in Messages

**Comment by mangerlahn** [comment]
Added with Merge 25d73198a272ea0f16d852dec45e30945fd56c01
