### ISSUE TITLE
Updates placeholder <dnl> on starting up

### ISSUE THREAD

**Issue by Drugsosos** [mangerlahn/Latest#291]
It's for a fraction of a second but still noticeable jitter on the screen

![image](https://github.com/mangerlahn/Latest/assets/44712637/23f1abec-1a08-420c-99cc-a5506ffcfe70)

---

Version 0.10 (1111)

**Comment by mangerlahn** [comment]
Thanks for the report!

**Comment by mangerlahn** [comment]
Fixed with 4b355ec
