### ISSUE TITLE
Error opening the application after updating to the latest version

### ISSUE THREAD

**Issue by marcelofares** [mangerlahn/Latest#292]
After I downloaded the latest version from the official website, the application no longer opens. The previous version was working perfectly.  I have the latest version of Sonoma 14.1.1

Here is the error:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Latest [5843]
Path:                  /Applications/Latest.app/Contents/MacOS/Latest
Identifier:            com.max-langer.Latest
Version:               0.10 (1111)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-28 18:00:12.3085 -0300
OS Version:            macOS 14.1.1 (23B81)
Report Version:        12
Bridge OS Version:     8.1 (21P1069)
Anonymous UUID:        2B30672E-5081-B5F0-1783-CFD419554B9B

Sleep/Wake UUID:       6A88CCF5-F28F-4C54-B913-A57A17BEFBCB

Time Awake Since Boot: 36000 seconds
Time Since Wake:       17652 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [5843]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Latest                        	       0x10d8e0136 0x10d8d5000 + 45366
1   Latest                        	       0x10d8e0198 0x10d8d5000 + 45464
2   AppKit                        	    0x7ff8137398c4 -[NSWindowController _windowDidLoad] + 553
3   CoreFoundation                	    0x7ff80ff75d7f -[NSSet makeObjectsPerformSelector:] + 231
4   AppKit                        	    0x7ff81356ece0 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1300
5   AppKit                        	    0x7ff8135e3439 -[NSNib _instantiateNibWithExternalNameTable:options:] + 659
6   AppKit                        	    0x7ff8135e30b1 -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
7   AppKit                        	    0x7ff814097e1e -[NSStoryboard _instantiateControllerWithIdentifier:creator:storyboardSegueTemplate:sender:] + 472
8   AppKit                        	    0x7ff813554dc8 NSApplicationMain + 744
9   Latest                        	       0x10d8f6b19 0x10d8d5000 + 138009
10  dyld                          	    0x7ff80fb1d3a6 start + 1942

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff80fea1b88 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff80fea1b88 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff80fea1b88 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x323dfff8534c19a9  rbx: 0x0000600002ebd220  rcx: 0x00007ffffffffff8  rdx: 0x0080000000000000
  rdi: 0x0000600003cb4000  rsi: 0x0100000000000000  rbp: 0x00007ff7b2629eb0  rsp: 0x00007ff7b2629e20
   r8: 0x313dfff8534c19a9   r9: 0x0000000092001153  r10: 0x0000000000000002  r11: 0x00000000000007fb
  r12: 0x0000000000000000  r13: 0x0000600002ebd220  r14: 0x0000600003cb4000  r15: 0x0000000000000001
  rip: 0x000000010d8e0136  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     8
Error Code:      0x00000000 
Trap Number:     6

Thread 0 instruction stream:
  06 00 ba 01 00 00 00 4c-89 ff e8 6f 97 04 00 48  .......L...o...H
  89 df 41 ff d4 4c 89 ff-41 ff d4 eb 09 48 89 df  ..A..L..A....H..
  ff 15 04 d5 05 00 48 83-c4 68 5b 41 5c 41 5d 41  ......H..h[A\A]A
  5e 41 5f 5d c3 48 8d 3d-d6 a5 06 00 48 8d 35 b7  ^A_].H.=....H.5.
  99 02 00 e8 9e 98 04 00-e9 03 fd ff ff bf 01 00  ................
  00 00 4c 89 f6 e8 70 40-04 00 eb 94 0f 0b 0f 0b  ..L...p@........
 [0f]0b 0f 0b 0f 57 c0 0f-29 45 c0 0f 29 45 b0 4c  .....W..)E..)E.L	<==
  89 ef e8 af 97 04 00 4c-89 e7 e8 a7 97 04 00 0f  .......L........
  0b 0f 57 c0 0f 29 45 c0-0f 29 45 b0 4c 89 e7 e8  ..W..)E..)E.L...
  92 97 04 00 4c 89 ef be-02 00 00 00 e8 8b 97 04  ....L...........
  00 0f 0b 0f 1f 80 00 00-00 00 55 48 89 e5 41 55  ..........UH..AU
  53 49 89 fd ff 15 78 d4-05 00 48 89 c3 e8 e8 f8  SI....x...H.....

Binary Images:
       0x10dba6000 -        0x10dbb5fff libobjc-trampolines.dylib (*) <98971a5a-9c10-3af1-8886-451f2945c39e> /usr/lib/libobjc-trampolines.dylib
       0x10d96a000 -        0x10d9adfff org.sparkle-project.Sparkle (2.5.1) <c48058fc-540e-3b1f-af01-3260e00c3e1d> /Applications/Latest.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x10d8d5000 -        0x10d93cfff com.max-langer.Latest (0.10) <1fb3c2b8-60b7-36d4-a2fe-05fcb2f0ad5f> /Applications/Latest.app/Contents/MacOS/Latest
    0x7ff813551000 -     0x7ff814956ffb com.apple.AppKit (6.9) <27fed5dd-d148-3238-bc95-1dac5dd57fa1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff80ff05000 -     0x7ff81039ffec com.apple.CoreFoundation (6.9) <d148cf66-0478-3100-a9d6-0571b6f769e3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff80fb17000 -     0x7ff80fbb33df dyld (*) <d5406f23-6967-39c4-beb5-6ae3293c7753> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff80fea0000 -     0x7ff80feabfff libsystem_pthread.dylib (*) <c64722b0-e96a-3fa5-96c3-b4beaf0c494a> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=827.8M resident=0K(0%) swapped_out_or_unallocated=827.8M(100%)
Writable regions: Total=642.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=642.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          208K       24 
Foundation                          16K        1 
Foundation (reserved)                4K        1         reserved VM address space (unallocated)
Kernel Alloc Once                    8K        1 
MALLOC                           632.5M       44 
MALLOC guard page                   32K        8 
STACK GUARD                       56.0M        4 
Stack                             9752K        4 
VM_ALLOCATE                         12K        3 
__CTF                               824        1 
__DATA                            34.0M      565 
__DATA_CONST                      39.1M      360 
__DATA_DIRTY                      1726K      207 
__FONT_DATA                        2352        1 
__LINKEDIT                       180.6M        5 
__OBJC_RO                         70.8M        1 
__OBJC_RW                         2157K        2 
__TEXT                           647.2M      587 
dyld private memory                260K        2 
mapped file                      181.2M       26 
shared memory                      780K       16 
===========                     =======  ======= 
TOTAL                              1.8G     1864 
TOTAL, minus reserved VM space     1.8G     1864 

-----------
Full Report
-----------

{"app_name":"Latest","timestamp":"2023-11-28 18:00:12.00 -0300","app_version":"0.10","slice_uuid":"1fb3c2b8-60b7-36d4-a2fe-05fcb2f0ad5f","build_version":"1111","platform":1,"bundleID":"com.max-langer.Latest","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.1.1 (23B81)","roots_installed":0,"name":"Latest","incident_id":"AB4B9067-61E1-47B0-AEE5-4FD6BA3EAFD8"}
{
  "uptime" : 36000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac20,1",
  "coalitionID" : 6721,
  "osVersion" : {
    "train" : "macOS 14.1.1",
    "build" : "23B81",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-28 18:00:12.3085 -0300",
  "codeSigningMonitor" : 0,
  "incident" : "AB4B9067-61E1-47B0-AEE5-4FD6BA3EAFD8",
  "pid" : 5843,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-11-28 18:00:12.1080 -0300",
  "procStartAbsTime" : 36340414312542,
  "procExitAbsTime" : 36340614406996,
  "procName" : "Latest",
  "procPath" : "\/Applications\/Latest.app\/Contents\/MacOS\/Latest",
  "bundleInfo" : {"CFBundleShortVersionString":"0.10","CFBundleVersion":"1111","CFBundleIdentifier":"com.max-langer.Latest"},
  "storeInfo" : {"deviceIdentifierForVendor":"624E0F25-7C80-52A4-B2A8-A3A09D683A1C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.max-langer.Latest",
  "crashReporterKey" : "2B30672E-5081-B5F0-1783-CFD419554B9B",
  "codeSigningID" : "com.max-langer.Latest",
  "codeSigningTeamID" : "VFABJ5RE5Q",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "wakeTime" : 17652,
  "bridgeVersion" : {"build":"21P1069","train":"8.1"},
  "sleepWakeUUID" : "6A88CCF5-F28F-4C54-B913-A57A17BEFBCB",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":5843},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":464559,"instructionState":{"instructionStream":{"bytes":[6,0,186,1,0,0,0,76,137,255,232,111,151,4,0,72,137,223,65,255,212,76,137,255,65,255,212,235,9,72,137,223,255,21,4,213,5,0,72,131,196,104,91,65,92,65,93,65,94,65,95,93,195,72,141,61,214,165,6,0,72,141,53,183,153,2,0,232,158,152,4,0,233,3,253,255,255,191,1,0,0,0,76,137,246,232,112,64,4,0,235,148,15,11,15,11,15,11,15,11,15,87,192,15,41,69,192,15,41,69,176,76,137,239,232,175,151,4,0,76,137,231,232,167,151,4,0,15,11,15,87,192,15,41,69,192,15,41,69,176,76,137,231,232,146,151,4,0,76,137,239,190,2,0,0,0,232,139,151,4,0,15,11,15,31,128,0,0,0,0,85,72,137,229,65,85,83,73,137,253,255,21,120,212,5,0,72,137,195,232,232,248],"offset":96}},"threadState":{"r13":{"value":105553165275680},"rax":{"value":3620331117490215337},"rflags":{"value":66118},"cpu":{"value":8},"r14":{"value":105553179918336},"rsi":{"value":72057594037927936},"r8":{"value":3548273523452287401},"cr2":{"value":0},"rdx":{"value":36028797018963968},"r10":{"value":2},"r9":{"value":2449477971},"r15":{"value":1},"rbx":{"value":105553165275680},"trap":{"value":6},"err":{"value":0},"r11":{"value":2043},"rip":{"value":4522377526,"matchesCrashFrame":1},"rbp":{"value":140701826457264},"rsp":{"value":140701826457120},"r12":{"value":0},"rcx":{"value":140737488355320},"flavor":"x86_THREAD_STATE","rdi":{"value":105553179918336}},"queue":"com.apple.main-thread","frames":[{"imageOffset":45366,"imageIndex":2},{"imageOffset":45464,"imageIndex":2},{"imageOffset":2001092,"symbol":"-[NSWindowController _windowDidLoad]","symbolLocation":553,"imageIndex":3},{"imageOffset":462207,"symbol":"-[NSSet makeObjectsPerformSelector:]","symbolLocation":231,"imageIndex":4},{"imageOffset":122080,"symbol":"-[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:]","symbolLocation":1300,"imageIndex":3},{"imageOffset":599097,"symbol":"-[NSNib _instantiateNibWithExternalNameTable:options:]","symbolLocation":659,"imageIndex":3},{"imageOffset":598193,"symbol":"-[NSNib _instantiateWithOwner:options:topLevelObjects:]","symbolLocation":143,"imageIndex":3},{"imageOffset":11824670,"symbol":"-[NSStoryboard _instantiateControllerWithIdentifier:creator:storyboardSegueTemplate:sender:]","symbolLocation":472,"imageIndex":3},{"imageOffset":15816,"symbol":"NSApplicationMain","symbolLocation":744,"imageIndex":3},{"imageOffset":138009,"imageIndex":2},{"imageOffset":25510,"symbol":"start","symbolLocation":1942,"imageIndex":5}]},{"id":464584,"frames":[{"imageOffset":7048,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":6403},"r8":{"value":409602},"cr2":{"value":0},"rdx":{"value":123145405100032},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145405623160},"rbx":{"value":123145405624320},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703395617672},"rbp":{"value":0},"rsp":{"value":123145405624320},"r12":{"value":5193730},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145405624320}}},{"id":464585,"frames":[{"imageOffset":7048,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":10499},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145405636608},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145406159744},"rbx":{"value":123145406160896},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703395617672},"rbp":{"value":0},"rsp":{"value":123145406160896},"r12":{"value":1982472},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145406160896}}},{"id":464595,"frames":[{"imageOffset":7048,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":17411},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145406173184},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145406696320},"rbx":{"value":123145406697472},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703395617672},"rbp":{"value":0},"rsp":{"value":123145406697472},"r12":{"value":1982472},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145406697472}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 4525285376,
    "size" : 65536,
    "uuid" : "98971a5a-9c10-3af1-8886-451f2945c39e",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4522942464,
    "CFBundleShortVersionString" : "2.5.1",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "c48058fc-540e-3b1f-af01-3260e00c3e1d",
    "path" : "\/Applications\/Latest.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2032"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4522332160,
    "CFBundleShortVersionString" : "0.10",
    "CFBundleIdentifier" : "com.max-langer.Latest",
    "size" : 425984,
    "uuid" : "1fb3c2b8-60b7-36d4-a2fe-05fcb2f0ad5f",
    "path" : "\/Applications\/Latest.app\/Contents\/MacOS\/Latest",
    "name" : "Latest",
    "CFBundleVersion" : "1111"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703452958720,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20996092,
    "uuid" : "27fed5dd-d148-3238-bc95-1dac5dd57fa1",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.20.107"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703396024320,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4829165,
    "uuid" : "d148cf66-0478-3100-a9d6-0571b6f769e3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2106"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703391903744,
    "size" : 639968,
    "uuid" : "d5406f23-6967-39c4-beb5-6ae3293c7753",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703395610624,
    "size" : 49152,
    "uuid" : "c64722b0-e96a-3fa5-96c3-b4beaf0c494a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703391207424,
  "size" : 25769803776,
  "uuid" : "4f1c5bcd-3ba7-365c-9e1f-56c2b41cafa6"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=827.8M resident=0K(0%) swapped_out_or_unallocated=827.8M(100%)\nWritable regions: Total=642.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=642.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          208K       24 \nFoundation                          16K        1 \nFoundation (reserved)                4K        1         reserved VM address space (unallocated)\nKernel Alloc Once                    8K        1 \nMALLOC                           632.5M       44 \nMALLOC guard page                   32K        8 \nSTACK GUARD                       56.0M        4 \nStack                             9752K        4 \nVM_ALLOCATE                         12K        3 \n__CTF                               824        1 \n__DATA                            34.0M      565 \n__DATA_CONST                      39.1M      360 \n__DATA_DIRTY                      1726K      207 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       180.6M        5 \n__OBJC_RO                         70.8M        1 \n__OBJC_RW                         2157K        2 \n__TEXT                           647.2M      587 \ndyld private memory                260K        2 \nmapped file                      181.2M       26 \nshared memory                      780K       16 \n===========                     =======  ======= \nTOTAL                              1.8G     1864 \nTOTAL, minus reserved VM space     1.8G     1864 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "6c3775f64b86d9d649fa0b00e609d41caff4a44e",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "63508beab3714d3622fc7808"
      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "632e3f9c01482c74ed76392d",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "651f75fdfb457e489b2ffa72"
      },
      "deploymentId" : 240000315
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac20,1, BootROM 2020.41.1.0.0 (iBridge: 21.16.1069.0.0,0), 6 processors, 6-Core Intel Core i5, 3,3 GHz, 16 GB, SMC 
Graphics: AMD Radeon Pro 5300, AMD Radeon Pro 5300, PCIe, 4 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Display: LG FULL HD, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: Slot 1 (Channel A / DIMM 1), 4 GB, DDR4, 2133 MHz, Samsung, M471A5244CB0-CTD
Memory Module: Slot 2 (Channel A / DIMM 0), 4 GB, DDR4, 2133 MHz, SK Hynix, HMA851S6DJR6N-VK
Memory Module: Slot 3 (Channel B / DIMM 1), 4 GB, DDR4, 2133 MHz, Micron, 4ATF51264HZ-2G6E1
Memory Module: Slot 4 (Channel B / DIMM 0), 4 GB, DDR4, 2133 MHz, SK Hynix, HMA851S6DJR6N-VK
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 10 2023 12:53:18 version 9.30.503.0.32.5.92 FWID 01-c06f991b
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Network Service: iPhone 2, Ethernet, en10
USB Device: USB31Bus
USB Device: Best USB Device
USB Device: 3639S
USB Device: iPhone
USB Device: T2Bus
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: iMac, Apple Inc., 58.2
![2023-11-28_18-00](https://github.com/mangerlahn/Latest/assets/33350931/ed870212-2a2f-4543-befa-12b91b3c51e4)

**Comment by mangerlahn** [comment]
Thanks for the report, will investigate!

**Comment by rckmath** [comment]
Same problem.
![image](https://github.com/mangerlahn/Latest/assets/38138775/25cf4ad9-cffc-4bdf-bee3-5621437c7501)

**Comment by igorlmatos** [comment]
I think I have the same problem. Just to give a little more information on the steps that gave me the error.

I tried to update Latest through itself, as if it were any other app. After that, the problem started happening. After that,  I tried uninstalling and installing the app again, but to no avail.

This is a great app, by the way.

**Comment by neiltonkdf** [comment]
Same problem here.

**Comment by marcelofares** [comment]
> Same problem here. Where can I download the old version?
> 
> i Found link for this.
> 
> https://github.com/mangerlahn/Latest/releases

This version 0.9 is working perfectly, different from version 0.10

**Comment by splorp** [comment]
Running into the same crash on startup, but running under High Sierra. Oddly enough, this version works fine on my MacBook Air (Early 2015) under High Sierra, but not my MacBook Pro (Mid 2015).

Here’s a link to the crash report, so as not to muddle this thread up any more.

https://gist.github.com/splorp/9c1a68430c19c5837974e192217f6fa9

**Comment by splorp** [comment]
The new build crashed on initial launch, but then opened correctly upon subsequent launches.

Here’s a link to the crash report.

https://gist.github.com/splorp/0262748b57d5c323afba4da66129888f

**Comment by splorp** [comment]
> So to make sure I got this right: Before, the app would crash on every launch, now it appears to work?

Correct.

**Comment by mangerlahn** [comment]
Should be fixed with the just released 0.10.1

**Comment by marcelofares** [comment]
> Thanks for your patience! Could you try out this build and check whether this fixes the crash? [Latest.zip](https://github.com/mangerlahn/Latest/files/13598355/Latest.zip)

This solved my problem and now I can run the latest version without crashing!
