### ISSUE TITLE
Left pane: "No Updates Available" vs right pane: "9 Updates Available"

### ISSUE THREAD

**Issue by pro-sumer** [mangerlahn/Latest#298]
![latest](https://github.com/mangerlahn/Latest/assets/44335102/59f06236-c628-47ab-bcf8-858b66bf10d8)
Clicking the reload/refresh button makes no difference...

What can I do now?

**Comment by mangerlahn** [comment]
Looks like you have something typed in the search bar. The "No Updates Available" here is misleading, will improve that :)

**Comment by pro-sumer** [comment]
> Looks like you have something typed in the search bar.

Indeed...

**Comment by mangerlahn** [comment]
Does everything work as expected now?

**Comment by pro-sumer** [comment]
No, unfortunately not, but I have reported/contributed that in other issues.

Please feel free to close this issue as PEBKAC...

**Comment by mangerlahn** [comment]
Clarified UI in eedc711
