### ISSUE TITLE
Wrong update reported for Raspberry Pi Imager (1.8.3; latest is 1.8.1)

### ISSUE THREAD

**Issue by pro-sumer** [mangerlahn/Latest#299]
Latest is reporting update 1.8.3 being available for the Raspberry Pi Imager software, but the latest version available on the [Raspberry Pi website](https://www.raspberrypi.com/software/) is 1.8.1.

**Comment by mangerlahn** [comment]
Looks like the most recent version is not yet available on their website: 
https://github.com/raspberrypi/rpi-imager/releases
