### ISSUE TITLE
Submit to Hombrew-Cask

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#30]
Latest is a lovely addition to Homebrew and Homebrew-Cask, and it'd be great for people to install and update Latest through Cask.

https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask

**Comment by mangerlahn** [comment]
Yes, that will be a good idea. Thanks!

**Comment by mangerlahn** [comment]
Done: https://github.com/Homebrew/homebrew-cask/pull/52013#pullrequestreview-155741983
