### ISSUE TITLE
Failure when opening app

### ISSUE THREAD

**Issue by fernando-magri** [mangerlahn/Latest#300]
Hello Max Langer, congratulations on your work is a great app, but unfortunately version 0.10 is not working on my MacBook Air M1, I will send the error description below.

Thanks!

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Latest [17654]
Path:                  /Applications/Latest.app/Contents/MacOS/Latest
Identifier:            com.max-langer.Latest
Version:               0.10 (1111)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-30 12:29:23.5066 -0300
OS Version:            macOS 14.1.1 (23B81)
Report Version:        12
Anonymous UUID:        55E83BBA-5208-1941-E741-50C16C1E0274

Sleep/Wake UUID:       0BE9CA19-2320-427A-91D8-57238BB97D96

Time Awake Since Boot: 20000 seconds
Time Since Wake:       9329 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000102e757c0

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [17654]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Latest                        	       0x102e757c0 0x102e6c000 + 38848
1   Latest                        	       0x102e75820 0x102e6c000 + 38944
2   AppKit                        	       0x190cbab44 -[NSWindowController _windowDidLoad] + 620
3   CoreFoundation                	       0x18d369cf0 -[NSSet makeObjectsPerformSelector:] + 176
4   AppKit                        	       0x190b31018 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 788
5   AppKit                        	       0x190b97bd8 -[NSNib _instantiateNibWithExternalNameTable:options:] + 332
6   AppKit                        	       0x190b979c4 -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 132
7   AppKit                        	       0x191520644 -[NSStoryboard _instantiateControllerWithIdentifier:creator:storyboardSegueTemplate:sender:] + 388
8   AppKit                        	       0x190b192c8 NSApplicationMain + 620
9   Latest                        	       0x102e8b224 0x102e6c000 + 127524
10  dyld                          	       0x18cf1d0e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x18d293e28 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18d293e28 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18d293e28 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600002b70140   x1: 0x32000001e346bb0d   x2: 0x00000001e346bb08   x3: 0x000060000062ce40
    x4: 0x0000000000000001   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x000000016cf92dc0
    x8: 0x00000001e3449fa0   x9: 0xe406a0a8ac8f006a  x10: 0x0000000000000e10  x11: 0x00000000a38847fb
   x12: 0x00000000000007fb  x13: 0x00000000000007fd  x14: 0x00000000a3a8484c  x15: 0x000000000000004c
   x16: 0x32000001e346bb0d  x17: 0x0000000000000062  x18: 0x0000000000000000  x19: 0x0000600003970f00
   x20: 0x0000600002b70140  x21: 0x0000000148615de0  x22: 0x0000000000000000  x23: 0x0000000000000038
   x24: 0x0000000102ed8000  x25: 0x000060000065f960  x26: 0x0000000000000000  x27: 0x0000002100000004
   x28: 0x0000000000000020   fp: 0x000000016cf92f70   lr: 0x0000000102e752d8
    sp: 0x000000016cf92ed0   pc: 0x0000000102e757c0 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x10312c000 -        0x103137fff libobjc-trampolines.dylib (*) <c9ce7923-2f2d-31eb-a6e4-0f3b7a78f895> /usr/lib/libobjc-trampolines.dylib
       0x10341c000 -        0x10345ffff org.sparkle-project.Sparkle (2.5.1) <f6d9e0bb-3dec-34d5-8524-32b314d93248> /Applications/Latest.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x102e6c000 -        0x102ecffff com.max-langer.Latest (0.10) <5773beec-f1b9-3a80-b885-8086de3df315> /Applications/Latest.app/Contents/MacOS/Latest
       0x190b15000 -        0x191e29fff com.apple.AppKit (6.9) <b475e541-691d-39c6-8ca4-e414b0d3dd88> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x18d2f8000 -        0x18d7cffff com.apple.CoreFoundation (6.9) <9f046e36-7286-3a6e-a280-699d6e47cfaf> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x18cf17000 -        0x18cfab317 dyld (*) <ec7a3ba0-f9bf-3ab8-a0f4-8622e5606b20> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18d292000 -        0x18d29eff3 libsystem_pthread.dylib (*) <daf95373-5de6-39a1-a6ce-d87f3f0629cc> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)
Writable regions: Total=842.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=842.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          528K       24 
CoreGraphics                        32K        2 
CoreServices                       256K        1 
Foundation                          16K        1 
Foundation (reserved)               16K        1         reserved VM address space (unallocated)
Kernel Alloc Once                   32K        1 
MALLOC                           832.3M       31 
MALLOC guard page                  192K       12 
STACK GUARD                       56.1M        4 
Stack                             9808K        4 
VM_ALLOCATE                         32K        2 
__AUTH                            2028K      353 
__AUTH_CONST                      29.4M      561 
__CTF                               824        1 
__DATA                            13.5M      549 
__DATA_CONST                      28.3M      569 
__DATA_DIRTY                      1894K      208 
__FONT_DATA                          4K        1 
__LINKEDIT                       886.6M        4 
__OBJC_RO                         70.8M        1 
__OBJC_RW                         2156K        1 
__TEXT                           628.7M      587 
dyld private memory                272K        2 
mapped file                      174.4M       25 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              2.7G     2959 
TOTAL, minus reserved VM space     2.7G     2959 

-----------
Full Report
-----------

{"app_name":"Latest","timestamp":"2023-11-30 12:29:25.00 -0300","app_version":"0.10","slice_uuid":"5773beec-f1b9-3a80-b885-8086de3df315","build_version":"1111","platform":1,"bundleID":"com.max-langer.Latest","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.1.1 (23B81)","roots_installed":0,"name":"Latest","incident_id":"21278E10-9020-4C17-917B-CB17AE07AA93"}
{
  "uptime" : 20000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 4769,
  "osVersion" : {
    "train" : "macOS 14.1.1",
    "build" : "23B81",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-30 12:29:23.5066 -0300",
  "codeSigningMonitor" : 1,
  "incident" : "21278E10-9020-4C17-917B-CB17AE07AA93",
  "pid" : 17654,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-11-30 12:29:23.0109 -0300",
  "procStartAbsTime" : 495990539357,
  "procExitAbsTime" : 496002344519,
  "procName" : "Latest",
  "procPath" : "\/Applications\/Latest.app\/Contents\/MacOS\/Latest",
  "bundleInfo" : {"CFBundleShortVersionString":"0.10","CFBundleVersion":"1111","CFBundleIdentifier":"com.max-langer.Latest"},
  "storeInfo" : {"deviceIdentifierForVendor":"C5148E2A-B37A-5404-898C-70801268C88A","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.max-langer.Latest",
  "crashReporterKey" : "55E83BBA-5208-1941-E741-50C16C1E0274",
  "codeSigningID" : "com.max-langer.Latest",
  "codeSigningTeamID" : "VFABJ5RE5Q",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"QQEAkCEwApEnFgGURv\/\/FyAAgFLhAxSqlAMBlOP\/\/xcgACDUIAAg1A==","atPC":"IAAg1CAAINQA5ABv4IMAreADFKq6FQGU4AMWqrgVAZQgACDUAOQAbw=="},
  "wakeTime" : 9329,
  "sleepWakeUUID" : "0BE9CA19-2320-427A-91D8-57238BB97D96",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000102e757c0","rawCodes":[1,4343683008],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":17654},
  "os_fault" : {"process":"Latest"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":239437,"threadState":{"x":[{"value":105553161814336},{"value":3602879710004427533,"symbolLocation":3602879701896396805,"symbol":"OBJC_CLASS_$_NSBundle"},{"value":8108030728,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSBundle"},{"value":105553122741824},{"value":1},{"value":0},{"value":0},{"value":6123236800},{"value":8107892640,"symbolLocation":224,"symbol":"_main_thread"},{"value":16430996936817836138},{"value":3600},{"value":2743617531},{"value":2043},{"value":2045},{"value":2745714764},{"value":76},{"value":3602879710004427533,"symbolLocation":3602879701896396805,"symbol":"OBJC_CLASS_$_NSBundle"},{"value":98},{"value":0},{"value":105553176497920},{"value":105553161814336},{"value":5509307872},{"value":0},{"value":56},{"value":4344086528},{"value":105553122949472},{"value":0},{"value":141733920772},{"value":32}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4343681752},"cpsr":{"value":1610616832},"fp":{"value":6123237232},"sp":{"value":6123237072},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4343683008,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":38848,"imageIndex":2},{"imageOffset":38944,"imageIndex":2},{"imageOffset":1727300,"symbol":"-[NSWindowController _windowDidLoad]","symbolLocation":620,"imageIndex":3},{"imageOffset":466160,"symbol":"-[NSSet makeObjectsPerformSelector:]","symbolLocation":176,"imageIndex":4},{"imageOffset":114712,"symbol":"-[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:]","symbolLocation":788,"imageIndex":3},{"imageOffset":535512,"symbol":"-[NSNib _instantiateNibWithExternalNameTable:options:]","symbolLocation":332,"imageIndex":3},{"imageOffset":534980,"symbol":"-[NSNib _instantiateWithOwner:options:topLevelObjects:]","symbolLocation":132,"imageIndex":3},{"imageOffset":10532420,"symbol":"-[NSStoryboard _instantiateControllerWithIdentifier:creator:storyboardSegueTemplate:sender:]","symbolLocation":388,"imageIndex":3},{"imageOffset":17096,"symbol":"NSApplicationMain","symbolLocation":620,"imageIndex":3},{"imageOffset":127524,"imageIndex":2},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":5}]},{"id":239458,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6123794432},{"value":4867},{"value":6123257856},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6123794432},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6663257640},"far":{"value":0}}},{"id":239459,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6124367872},{"value":8451},{"value":6123831296},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6124367872},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6663257640},"far":{"value":0}}},{"id":239461,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6124941312},{"value":20739},{"value":6124404736},{"value":0},{"value":409602},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6124941312},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6663257640},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4346527744,
    "size" : 49152,
    "uuid" : "c9ce7923-2f2d-31eb-a6e4-0f3b7a78f895",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4349607936,
    "CFBundleShortVersionString" : "2.5.1",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "f6d9e0bb-3dec-34d5-8524-32b314d93248",
    "path" : "\/Applications\/Latest.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2032"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4343644160,
    "CFBundleShortVersionString" : "0.10",
    "CFBundleIdentifier" : "com.max-langer.Latest",
    "size" : 409600,
    "uuid" : "5773beec-f1b9-3a80-b885-8086de3df315",
    "path" : "\/Applications\/Latest.app\/Contents\/MacOS\/Latest",
    "name" : "Latest",
    "CFBundleVersion" : "1111"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6722506752,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20008960,
    "uuid" : "b475e541-691d-39c6-8ca4-e414b0d3dd88",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.20.107"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6663667712,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "9f046e36-7286-3a6e-a280-699d6e47cfaf",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2106"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6659600384,
    "size" : 607000,
    "uuid" : "ec7a3ba0-f9bf-3ab8-a0f4-8622e5606b20",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6663249920,
    "size" : 53236,
    "uuid" : "daf95373-5de6-39a1-a6ce-d87f3f0629cc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6658850816,
  "size" : 4018896896,
  "uuid" : "80dd42b3-8a52-3caf-9848-54a1c2732864"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)\nWritable regions: Total=842.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=842.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          528K       24 \nCoreGraphics                        32K        2 \nCoreServices                       256K        1 \nFoundation                          16K        1 \nFoundation (reserved)               16K        1         reserved VM address space (unallocated)\nKernel Alloc Once                   32K        1 \nMALLOC                           832.3M       31 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.1M        4 \nStack                             9808K        4 \nVM_ALLOCATE                         32K        2 \n__AUTH                            2028K      353 \n__AUTH_CONST                      29.4M      561 \n__CTF                               824        1 \n__DATA                            13.5M      549 \n__DATA_CONST                      28.3M      569 \n__DATA_DIRTY                      1894K      208 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       886.6M        4 \n__OBJC_RO                         70.8M        1 \n__OBJC_RW                         2156K        1 \n__TEXT                           628.7M      587 \ndyld private memory                272K        2 \nmapped file                      174.4M       25 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              2.7G     2959 \nTOTAL, minus reserved VM space     2.7G     2959 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "c2c21b0726b515bafda8b5605570086e950b93f3",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "632e3df958740028737bffc0",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "654e391a4a6560536bdb1c80"
      },
      "deploymentId" : 240000529
    },
    {
      "rolloutId" : "632e3f9c01482c74ed76392d",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "651f75f5fb457e489b2ffa70"
      },
      "deploymentId" : 240000315
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000019
    }
  ]
}
}

Model: MacBookAir10,1, BootROM 10151.41.12, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Display: LG HDR WFHD, 2560 x 1080 (UW-UXGA - Ultra Wide - Ultra Extended Graphics Array), MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Aug 26 2023 17:55:53 version 18.20.439.0.7.8.163 FWID 01-f9b9247b
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB 2.0 Hub
USB Device: USB Type-C Digital AV Adapter
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by mangerlahn** [comment]
I attached an updated build in #292, not sure if this fixes the issue as I can't reproduce it myself. Could you give it a try?
