### ISSUE TITLE
Deepl

### ISSUE THREAD

**Issue by ffurger** [mangerlahn/Latest#314]
Latest believes there is a new version of DeepL, but DeepL disagrees:
your version 23.9.1591123
New version: 23.10.1631621

**Comment by mangerlahn** [comment]
Thanks for the report! There appears to be a newer version (23.10) [here](https://www.deepl.com/macos/download/23.10.1631621/DeepL_23.10.1631621.zip). Not sure why the website delivers the older 23.9

**Comment by ffurger** [comment]
No, thank you for developing this terrific application!Sent from my iPadOn Dec 9, 2023, at 22:05, Max Langer ***@***.***> wrote:﻿
Thanks for the report! There appears to be a newer version (23.10) here. Not sure why the website delivers the older 23.9
