### ISSUE TITLE
Just downloaded the new version. It's saying all the microsoft apps need to be updated

### ISSUE THREAD

**Issue by MrMLK** [mangerlahn/Latest#315]
![CleanShot 2023-12-09 at 16 21 29@2x](https://github.com/mangerlahn/Latest/assets/241619/e7f9327b-16cf-4364-bd59-7e8f973f29b4)

Look at Outlook. I'm on 16.79.3 and latest is tellng me to update to 16.79.23xxxx

**Comment by MrMLK** [comment]
It's also saying Adobe Acrobat needs updating which Adobe is not finding.

**Comment by dhaun** [comment]
Yes, same here. I guess something about comparing the version numbers isn't correct.

<img width="606" alt="latest" src="https://github.com/mangerlahn/Latest/assets/16507691/fdd5a487-acaa-4115-9f62-eaae27be9985">

**Comment by pro-sumer** [comment]
I also see this for Outlook, Word, Excel, and PowerPoint, but not for Teams.

**Comment by theoldcoot** [comment]
Me to. Going back to the previous version.

**Comment by mangerlahn** [comment]
Fixed in v0.10.2
