### ISSUE TITLE
SilentKnight updated detected where there is none

### ISSUE THREAD

**Issue by foss-** [mangerlahn/Latest#316]
Vesion installed and detected: 2.7 (38)
New version: 2.07

Download at https://eclecticlightdotcom.files.wordpress.com/2023/11/silentknight207.zip suggests 207 maybe involved somewhere.

![1](https://github.com/mangerlahn/Latest/assets/5708172/154e3ea0-e894-47d4-9614-3420dcbdca7b)

PS: Thanks for the recent updates. A ton of apps are now detected which previously never showed updates, which is much appreciated. Thanks for your work.

**Comment by acrostich** [comment]
Note that this also affects many others of Howard Oakley's great apps. (They're all available at https://eclecticlight.co/downloads/)

Of the ones I installed, also affected are: Spundle, Metamer, Mints, Cirrus, xattred, LockRattler, XProCheck, Ulbow, TheTimeMachineMechanic and Signet.

**Comment by foss-** [comment]
Resolved in Version 0.10.2 (1183)
