### ISSUE TITLE
Still many false reports in version 0.10.1 (1168)

### ISSUE THREAD

**Issue by pro-sumer** [mangerlahn/Latest#318]
Thank you for improving Homebrew support.

Unfortunately I still see many false reports in version 0.10.1 (1168), for Apps which I did not install using Homebrew.

Some have already been reported ([Microsoft](https://github.com/mangerlahn/Latest/issues/315), [SilentKnight](https://github.com/mangerlahn/Latest/issues/316)), but other not, so sharing a screenshot. Hope this helps.

<img width="813" alt="updates" src="https://github.com/mangerlahn/Latest/assets/44335102/b15f7312-8174-45c8-a345-e6f29efeb26e">

I checked all Apps in the screenshot. None have an update available.

PS: Would also appreciate some extra (vertical) spacing between labels (date and App name)

**Comment by JLP04** [comment]
I'm getting a bunch as well: 

Unity Hub showing Unity version for New Version:
<img width="300" alt="Screenshot 2023-12-10 at 4 05 55 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/591110f4-0643-4698-a040-3fc9e49c5672">

This app is part of Bricklink Studio but is only used to update Bricklink Studio and thus has different version numbers: 
<img width="297" alt="Screenshot 2023-12-10 at 4 06 00 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/6231a03d-b423-4609-9fba-0051b7591c6d">

I'm pretty sure this doesn't necessarily have the same version as regular Adobe Air: 
<img width="297" alt="Screenshot 2023-12-10 at 4 06 05 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/419258be-201a-4352-9960-219ae2f7f8d3">

**Comment by JLP04** [comment]
I'm also getting a false positive on RealVNC Viewer: 
<img width="315" alt="Screenshot 2023-12-10 at 4 09 31 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/3f3f910f-df65-4f82-83c3-58fc7bdeb42c">

And there's been this false positive on the App Store version of Cinebench for years: 
<img width="299" alt="Screenshot 2023-12-10 at 4 08 45 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/ac335c17-47b1-4980-ad90-05261734f849">

**Comment by pro-sumer** [comment]
All issues that I reported in this issue are solved in version 0.10.2 (1183) 🎉 

Thank you!

**Comment by pro-sumer** [comment]
(@JLP04 If your Apps are still reported wrong maybe you can submit a new issue for 0.10.2?)
