### ISSUE TITLE
False positive on IntelliJ IDEA CE

### ISSUE THREAD

**Issue by stephansann** [mangerlahn/Latest#324]
Hi!

First of all thanks a lot for this unbelievable helpful tool 🙏🏻

I found a small problem with IntelliJ IDEA CE:

<img width="367" alt="Screenshot 2023-12-14 at 10 08 04" src="https://github.com/mangerlahn/Latest/assets/9678681/351d39f3-b145-48f4-8fa9-b867f50a5649">

It seems that Latest is mixing up the professional and the community edition.

Best regards
Stephan

**Comment by mantasio** [comment]
I can confirm the same behavior for other JetBrains IDEs - WebStorm and Rider

**Comment by mangerlahn** [comment]
Are you still able to reproduce this?

**Comment by mantasio** [comment]
@mangerlahn I cannot reproduce this anymore, thank you!

**Comment by stephansann** [comment]
@mangerlahn For me it also looks fine now. Thanks a lot 🙏🏻

**Comment by mangerlahn** [comment]
Thanks!
