### ISSUE TITLE
A few more false positives in 0.10.1

### ISSUE THREAD

**Issue by nriley** [mangerlahn/Latest#326]
<img width="281" alt="image" src="https://github.com/mangerlahn/Latest/assets/68303/df65cf3d-27a7-4182-8962-92f3278053e6">

Jabra Firmware Update seems to be getting the Jabra Direct version number (they are packaged together, should not really show up as 2 apps).

Sublime Text 4168 shows as current in the app.

Thanks for the awesome improvements recently in completeness and stability!

**Comment by mangerlahn** [comment]
Thanks for the report! Sublimes website states that 4169 is the current version. Ill take a look at the Jabra thing.

**Comment by nriley** [comment]
Ahh right, the dev builds use a different numbering system in which 4168 is latest. (https://www.sublimetext.com/dev) Not sure if you can match the current version to tell if it's a dev or stable build?

**Comment by mangerlahn** [comment]
Is the issue with Jabra still there?

**Comment by nriley** [comment]
Nope, seems to be gone! I just see Jabra Direct with a (real) update.

<img width="235" alt="image" src="https://github.com/mangerlahn/Latest/assets/68303/b8bdaa79-c795-4584-8f6a-6ccf89dd0d17">
