### ISSUE TITLE
Handbrake shows updates while on latest version

### ISSUE THREAD

**Issue by foss-** [mangerlahn/Latest#341]
Handbrake shows updates while on latest version:

![1](https://github.com/mangerlahn/Latest/assets/5708172/e933bafb-ce11-4a5d-bf4c-c8b9f3903c87)

When checking in HandBrake no update is found.

**Comment by mangerlahn** [comment]
Weird, "your" and "new" version look the same. I can't reproduce that on my end, is it still an issue for you?

**Comment by foss-** [comment]
Yeah it made no sense. Think I hid that entry - when I now search for Handbrake no entries shows up. Unsure how to unhide.

**Comment by mangerlahn** [comment]
You can go to "View" → "Show Ignored Apps", it should appear there.

**Comment by foss-** [comment]
Confirming this seems to be resolved now. Timestamp is also no longer shown in brackets along the entry.
