### ISSUE TITLE
xACT not detecting available upgrade

### ISSUE THREAD

**Issue by FlavioB79** [mangerlahn/Latest#343]
Hi.
First time user of Latest, was wondering why some apps (in this case I'm picking just one out of many) do not show that an upgrade is available.
For example xACT: I've version 2.50 installed, which is correctly reported by Latest. The problem is, that Latest is not showing me the available upgrade (2.54)
![image](https://github.com/mangerlahn/Latest/assets/34163911/8d2d1e48-202c-4654-a575-840bb91d4fb9)

![image](https://github.com/mangerlahn/Latest/assets/34163911/8d9a82df-e848-4d4a-876e-8067bdef0cfe)
Is this a known bug/issue? Or is there something I didn't yet see/configure/understand?
Thanks!
F.

**Comment by gingerbeardman** [comment]
The fact that it is in the left sidebar *means* there is an update available. 

Just right click the app in the sidebar and choose update.

**Comment by FlavioB79** [comment]
I'll try this next time.
F.

https://www.instagram.com/boniforti_music
https://soundcloud.com/boniforti_music
https://bonny-j.bandcamp.com


Am So., 28. Jan. 2024 um 21:18 Uhr schrieb Matt Sephton <
***@***.***>:

**Comment by mangerlahn** [comment]
> The fact that it is in the left sidebar means there is an update available.

Not necessarily, you can also show installed apps without update available in Latest. Setting is in the "View" main menu.

I tried to reproduce this and downloaded the older v2.50. For me, the update is shown correctly, is this still an issue for you?

**Comment by FlavioB79** [comment]
> > The fact that it is in the left sidebar means there is an update available.
> 
> Not necessarily, you can also show installed apps without update available in Latest. Setting is in the "View" main menu.
> 
> I tried to reproduce this and downloaded the older v2.50. For me, the update is shown correctly, is this still an issue for you?

Hi - it's not an issue anymore. I tried the same: downloaded 2.50, then ran Latest and it now shows the available upgrade to 2.54
I think something has changed in Latest maybe?! Otherwise I can't explain it, as xACT 2.54 was already available 2 weeks ago (when I opened this issue).

F.

**Comment by mangerlahn** [comment]
Weird, if you see the issue again, feel free to reopen this issue :)
