### ISSUE TITLE
Ability to filter apps that are flagged as being able to update within themselves

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#346]
I'd prefer to not see apps that are being flagged as being able to update within themselves.

Too often, I launch the app and it contains to auto-update mechanism.

Ideally I'd prefer not to see apps that will update themselves. If I'm using the app, it will update as I use it. If I'm not using the app frequently enough for it to auto-update, or using it with no need to update, then I don't want it updating.

Also, some other issues present themselves from not being able to filter apps by update type: #311

**Comment by mangerlahn** [comment]
Yes, this is planned for the next update. It will be a filter for all apps that can't be updated from within Latest though. Determining whether apps update themselves is not really possible. Brew casks have a field for that, but it also includes Sparkle-based apps, as they are considered "self-updating" from brews pov.

**Comment by gingerbeardman** [comment]
Works for me!

**Comment by mangerlahn** [comment]
Resolved with ef559bdf9583f565b883f250796d3881d8d42832
