### ISSUE TITLE
FR: Bring Latest to Tray Bar (right top corner) and starts up after login

### ISSUE THREAD

**Issue by pthoelken** [mangerlahn/Latest#347]
Is there a way to bring Latest in background running mode up to the system tray icon bar (right top corner) and also starts latest up with my login? 

So, like the funktion from MacUpdater2 but I like your app more bc it's more comfortable and clean.

**Comment by mangerlahn** [comment]
Thanks for your request! This is planned in #64 and #53, but I have not gotten around to doing it.
