### ISSUE TITLE
auto update to all available updates or having a button to update all 

### ISSUE THREAD

**Issue by krashnakant** [mangerlahn/Latest#351]
Hello, 

Possible to have auto update to all out dated button would be really use full. updating 1 by 1 takes time. 

Really appreciate your effort you are making.

BR,Krashna

**Comment by AushevAhmad** [comment]
Latest has a button to update all apps (that is possible to update) but it doesn't have an auto update feature, at least yet.

**Comment by mangerlahn** [comment]
Currently not all apps are updatable within Latest. The "Update All" button updates all apps that are. There will be a setting soon that allows to filter apps which can't be updated within Latest. Implementing the update mechanism for these apps will take more time.

**Comment by mangerlahn** [comment]
Duplicate of #288
