### ISSUE TITLE
How does checking for the new package version work?

### ISSUE THREAD

**Issue by barseghyanartur** [mangerlahn/Latest#354]
First of all, thanks so much for this app!

----

Say, I'm an open-source app maintainer (published here, on GitHub). I want updates to my app to be discovered by Latest.

I couldn't find a methodology in the documentation to help me with that. Therefore, a couple of questions here:

- Which package meta information does Latest rely on?
- Are there any requirements for to the format of GitHub releases?

**Comment by mangerlahn** [comment]
Hi!

There are currently 3 sources Latest retrieves update information from:

- **App Store**: If the app is in the Mac App Store, Latest will fetch update info using the iTunes API
- **Sparkle**: If the app uses the Sparkle framework to allow self-updating, the app can also be checked by Latest. Requirement: The sparkle feed url needs to be set using the `SUFeedURL` key in `Info.plist`.
- **Homebrew Casks**: Recently Latest gained support for checking apps in the homebrew directory. However, this is not yet really stable and I get many reports for apps that don't work. Requirements: The cask file needs to contain the correct app name and bundle identifier. The version info should match what you have in the Info.plist file.

Github releases are not (yet) supported. Hope this helps :)
