### ISSUE TITLE
Version info getting clipped due to wrapping for apps with very long names

### ISSUE THREAD

**Issue by luckman212** [mangerlahn/Latest#361]
Minor UI issue, but for apps with very long names, the version info is being clipped in the view due to wrapping.

Here's one example ([Microsoft Azure Storage Explorer](https://azure.microsoft.com/en-us/products/storage/storage-explorer)):

![screenshot_puLCPq42](https://github.com/mangerlahn/Latest/assets/1992842/0b71a4a7-98a7-4235-83f8-f6ff49289ac5)

**Comment by mangerlahn** [comment]
Resolved with [6322871](https://github.com/mangerlahn/Latest/commit/63228711486e1a16c218ff31f8579fe807f5d2d2)
