### ISSUE TITLE
No more updates shown since macOS 14.4

### ISSUE THREAD

**Issue by khe91** [mangerlahn/Latest#366]
Latest.app 0.10.3
Since the macOS 14.4 update 
- no more updates are detected
- the list of installed apps is very short, only a few are listed

**Comment by khe91** [comment]
macOS 14.4.1 solves it. Now it's working again and shows all available updates.

**Comment by Gelioks** [comment]
I'm not seeing updates since the update to 14.6. Previously had a similar issue with 14.4 as @khe91
