### ISSUE TITLE
"App is damaged"-alert on v0.4.4

### ISSUE THREAD

**Issue by Mortennn** [mangerlahn/Latest#37]
The workaround is to use: "sudo spctl --master-disable".
It is properly some kind of codesign error, but i don't know.
Btw, awesome app so far!😀

**Comment by mangerlahn** [comment]
Sweet, once you automate update signing and distribution, everything breaks 🙄. Thanks for the hint, I will look into that! 😊

**Comment by mangerlahn** [comment]
Thank you so much for reporting. It was indeed an code signing issue. The new version (0.4.5) is now available and should be fine. 

I wonder why updates were fine, just newly downloaded binaries were affected..

And don't forget to reenable Gatekeeper, its there for safety ☺️

**Comment by Mortennn** [comment]
Glad you solved the issue👍
