### ISSUE TITLE
App unresponsive for a short while after "Update (in appname)" is clicked

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#372]
![image](https://github.com/mangerlahn/Latest/assets/49612/4dc9d535-a8b5-4004-869e-b44c48946634)

1. click "Update (in appname)"
2. try to navigate to a different app using the sidebar

Expected
- app should be responsive immediately after button is pressed

Actual
- app interface is locked/unresponsive until app is launched

**Comment by mangerlahn** [comment]
Thanks for the report!
This has been fixed in #360 and will be part of the next release :)

**Comment by gingerbeardman** [comment]
Thanks as always
