### ISSUE TITLE
setting to show only auto-updating apps

### ISSUE THREAD

**Issue by ShlomoCode** [mangerlahn/Latest#374]
I use Latest to auto-update multiple apps, but apps that don't support auto-update I prefer not to appear in the list, and when I open them they ask to update manually.

It would be nice to add in the settings an option to hide outdated apps that cannot be updated automatically.

**Comment by mangerlahn** [comment]
Thank you for reaching out! This has also been requested in https://github.com/mangerlahn/Latest/issues/346 and was already implemented. This feature will be part of the next update :)
