### ISSUE TITLE
Highlighted Release Notes

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#38]
Is there any way to make release notes with highlighting behave a bit better?
I admit this is a bit of a niche issue. Even if you could strip the highlight formatting out of the text.

Here's an example:
<img width="812" alt="screen shot 2018-10-11 at 4 34 15 pm" src="https://user-images.githubusercontent.com/12989893/46832261-93d5de00-cd73-11e8-9add-96c29fffeb0e.png">
<img width="1192" alt="screen shot 2018-10-11 at 4 34 04 pm" src="https://user-images.githubusercontent.com/12989893/46832265-96383800-cd73-11e8-9506-f003c7716eab.png">

**Comment by mangerlahn** [comment]
Ouch, I forgot to strip those. I would do so for now, since the release notes are (currently) rich text, so a nicer styling of these is not possible at the moment.

**Comment by mangerlahn** [comment]
Fixed in 0064eb8
