### ISSUE TITLE
Problems with updating two apps

### ISSUE THREAD

**Issue by HaoLeFok** [mangerlahn/Latest#381]
Hi, When I try to update two specific apps, something doesn't seem to be working properly. For Gris, it loads but does not complete the update without an error message. With Obsidian, the Obisidan app opens directly and it already says that it is on the latest version. I have also made a video of it and attached it to this post.

**Comment by aune-anx** [comment]
If you go to About Obsidian, it says this: Version 1.6.3 (Installer 1.5.12). I think Latest grabs the installer-version instead of the real version of Obsidian.

**Comment by HaoLeFok** [comment]
It just opens Obsidian and I have to manually update and restart, but that’s ok.
