### ISSUE TITLE
Add Cask Installation to README

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#39]
We should add the Homebrew install to the README installation instructions:

Latest can also be installed via [Homebrew] (https://brew.sh) with `brew cask install latest`.

**Comment by mangerlahn** [comment]
Good catch! Fixed in 24861c730bd9fa8f9dbad31b65f2d5f3ad6f3560.
Thanks!

**Comment by mangerlahn** [comment]
Sorry, just saw you already suggested a text. I wrote a new one simply because I did not look at the issue before.
