### ISSUE TITLE
latest icon

### ISSUE THREAD

**Issue by adrian-m77** [mangerlahn/Latest#390]
Hi. Do you have the app icon in higher resolution and quality? Is the app project still going ahead or has it been discontinued? Thanks.

**Comment by mangerlahn** [comment]
Hi Adrian,

I have a 2048x2048px version:
![2048](https://github.com/user-attachments/assets/d2733511-8ef9-41b7-b9cc-c5d60f910daa)

What do you need that for?

While the project has not been discontinued, it was hard to find the time (and motivation really) to get going again.

**Comment by adrian-m77** [comment]
Hello. Thank you for sending me the app logo, I am too "maniacal" with app icons. I don't like "Flat Design" and I always look for a homogeneous environment with quality icon sources. I am waiting for new updates to the app so that it is compatible with more apps. Thank you. I will try to contribute a donation of money to the project.

**Comment by mangerlahn** [comment]
Thank you!
I don't quite understand what you mean with regards to the icon. Is there anything I can do?

**Comment by adrian-m77** [comment]
No thanks, I just needed an icon with a little more quality. I like to change the icons of the applications for others with a little more graphic quality. Thank you very much. I have already donated money to the project. Kind regards.
