### ISSUE TITLE
Mangerfahn

### ISSUE THREAD

**Issue by BesBettison** [mangerlahn/Latest#393]
Look Great 👍

**Comment by BesBettison** [comment]
On assignee

**Comment by mangerlahn** [comment]
I am sorry, but I don't understand. What is this issue about?

**Comment by BesBettison** [comment]
Google map there is a voice giving a command , distance,turn right or left, ,when you use the service,it is similar to this scenario ,just apply in camera ,in addition the camera voice can read out various objects,for this implement the Blind or the poor vision people to use,by listening the command of the camera they use it for daily routine.great thank.
