### ISSUE TITLE
Weird Text Rendering Issue

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#41]
Came across a weird bug in the latest Geekbench release notes, there seems to be multiple layers of text being rendered onto of one another. Restarting the app seems to have no affect.
<img width="1440" alt="screen shot 2018-11-13 at 6 37 48 pm" src="https://user-images.githubusercontent.com/12989893/48450234-7ed5db80-e773-11e8-8f50-772ccb6fd691.png">

Edit: Reproduced on a second system. And you can see in the screenshot two distinct sets of characters. 
Here's a shot of the native release notes, looks like it's using a custom font, that may have something to do with it.
<img width="732" alt="screen shot 2018-11-15 at 3 15 18 pm" src="https://user-images.githubusercontent.com/12989893/48579051-64be0980-e8e9-11e8-94af-38d3ba5b992a.png">

**Comment by mangerlahn** [comment]
Huh, strangely close to #38, this time it was the text shadow attribute. Fixed in f2f5a97cf89229c147067d7ddaf5df41c20b0e47
