### ISSUE TITLE
Ignore apps managed by Setapp

### ISSUE THREAD

**Issue by agoeb** [mangerlahn/Latest#42]
I am a subscriber to [Setapp](https://setapp.com), which comes with its own app distribution and update channel. Often this means that Latest will show a new version of an app (e.g. today for Timing), which is not available via Setapp yet, but will be in a few hours or days.

All apps managed by Setapp are located in `/Applications/Setapp`. I would highly appreciate either ignoring those (probably easier) or showing only updates that are actually available via Setapp.
It seems that some sub-folder handling is already available because of #22.

**Comment by mangerlahn** [comment]
I am ignoring the folder for now. Nothing is more annoying than seeing an update that is not even available yet ;)
