### ISSUE TITLE
Update All -> As Sequence

### ISSUE THREAD

**Issue by muescha** [mangerlahn/Latest#43]
# what i do:

- i open latest
- i click on the 6 points icon

# what i see:

- i get an warning about opening 16 Apps 
- i not have done it because opening that many apps all with a update notice is not nice to handle

# what i expect:

- if an update is completed and detected from latest (the app is removed from the list) 
- the next app should be selected and details should be visible
- after a counter of 5/10 seconds then the next app should be opened
- i should be able to cancel the automatic countdown

**Comment by mangerlahn** [comment]
Yeah, "Open All" is pretty rough at the moment ;)
