### ISSUE TITLE
Progress bar difficult to see on highlighted row

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#50]
![Screen shot 2019-09-02 at 22 41 31](https://user-images.githubusercontent.com/49612/64134094-e3c9f300-cdd2-11e9-9627-4503ab039822.png)

**Comment by mangerlahn** [comment]
Note to self: Maybe `NSProgressIndicator.controlTint` can help hear..

**Comment by mangerlahn** [comment]
Okay, the control tint is not what I was looking for. I will fix this with rebuilding that UI for #60 .

**Comment by mangerlahn** [comment]
Fixed in 6384414
![Bildschirmfoto 2020-12-04 um 17 24 09](https://user-images.githubusercontent.com/11056766/101188245-bdd67280-3655-11eb-8b42-18a189a00c9c.png)
