### ISSUE TITLE
6.1 (337) View/Show

### ISSUE THREAD

**Issue by big610** [mangerlahn/Latest#52]
Max thanks for the quick turn around solving 6.0, to 6.1.
6.1 every time you opens shows no content blank grey showing/stating No Updates Available, top Banner Up to Date!
To fix, Requires every time you run, must re-load to fix:
View/Show Installed Updates. Can you fix like Version 5 (265) and earlier to automatically load to Show content?
I also had one 6.1 Crash Close, saved the report, if you want me to send to you.

macOS Mojave 10.14.6. What version are you using? 
Enjoy your app thoroughly, thanks for discovering.

**Comment by mangerlahn** [comment]
Thanks for pointing out! Your issues are also documented in #54 and #55, so I will close this issue.
