### ISSUE TITLE
Crash during Update Check

### ISSUE THREAD

**Issue by mangerlahn** [mangerlahn/Latest#54]
I get reports that the crash I attempted to fix in 0.6.1 (#46) is still there. This needs further investigation.

**Comment by gingerbeardman** [comment]
Interesting, as I stated in 46 the new build works for me (albeit with a long launch)

**Comment by mangerlahn** [comment]
I changed the update checking mechanism. This might fix this problem. Could you try this "beta" and see if it works?
https://max.codes/latest/Latest_0.6.2_Beta.zip

**Comment by mangerlahn** [comment]
I did not encounter any more crashes since changing the implementation.
