### ISSUE TITLE
Latest hangs on startup

### ISSUE THREAD

**Issue by linuxneverdies** [mangerlahn/Latest#56]
The application hangs on startup, I added the report.
[Latest_2019-09-03-210752_Hajos-iMac.hang.txt](https://github.com/mangerlahn/Latest/files/3571089/Latest_2019-09-03-210752_Hajos-iMac.hang.txt)

**Comment by gingerbeardman** [comment]
On mine with 200+ apps it takes 20+ bounces of the dock icon to start.

How long did you leave it?

**Comment by mangerlahn** [comment]
I changed the update checking mechanism. This might fix this problem. Could you try this "beta" and see if it works?
https://max.codes/latest/Latest_0.6.2_Beta.zip

**Comment by linuxneverdies** [comment]
It works now, thanks!

**Comment by mangerlahn** [comment]
Great!
