### ISSUE TITLE
Release notes stay on screen after app is updated and removed from list

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#57]
This is how Latest looked after I updated GraphicConverter 10

- no app in list
- release notes still displayed
- button says "update" but app has already been updated

## Screenshot

![Screen shot 2019-09-05 at 11 05 30](https://user-images.githubusercontent.com/49612/64333605-d0837700-cfce-11e9-96a2-039d927c1d17.png)

**Comment by gingerbeardman** [comment]
Still there in latest beta.

This screen from after apps were updated/redownlaoded through Mac App Store.

![Screen shot 2019-10-07 at 12 10 37](https://user-images.githubusercontent.com/49612/66307150-878b4f00-e8fb-11e9-9bb1-b4e4399d86e6.png)

**Comment by mangerlahn** [comment]
Jup I did not fix this one yet. I wanted to make sure the crashes and performance bottlenecks are gone.

**Comment by mangerlahn** [comment]
Fixed with 377d95634a225753afd3fafddf93a1f687bfdbff
