### ISSUE TITLE
Save List of Apps

### ISSUE THREAD

**Issue by big610** [mangerlahn/Latest#58]
Max since your working to fix 6.1 & 6.0 crashing & loading, pulling it apart, I wanted to suggest some Features. 

Total ## of Apps. Currently you provide just ## Updates Available.
Ability to save a list of Apps. File/Save List and File/Copy List to Clipboard.

These features can help you with troubleshooting load time, even though version 5, has no lag time can handle any amount, and we can save a list to send you upon request.

**Comment by mangerlahn** [comment]
I'd like to have every feature in its own issue, so I created another one for the first feature request. Feel free to comment there as well :)

**Comment by mangerlahn** [comment]
How would you like to have such a feature implemented? Would you like to get a list of only apps with updates, or all apps?

How should that list be formatted? Something like "Slack, Latest, Ulysses"?

**Comment by mangerlahn** [comment]
Closing in favor of #281
