### ISSUE TITLE
Cancel update control is difficult to press due to small size

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#60]
Tiny cross next to progress bar.

![Screen shot 2019-09-02 at 22 41 31](https://user-images.githubusercontent.com/49612/64134094-e3c9f300-cdd2-11e9-9627-4503ab039822.png)

**Comment by mangerlahn** [comment]
I'll probably have to rethink this UI to make it appear more like the Mac App Store equivalent of a circle that is both the progess bar and cancel button. This probably means removing the exact data (39 of 213MB) but oh well :D

**Comment by mangerlahn** [comment]
With rebuilding this UI, we need to consider better contrasts when the row is selected. See #50 for details-

**Comment by mangerlahn** [comment]
Fixed in 6384414
![Bildschirmfoto 2020-12-04 um 17 24 09](https://user-images.githubusercontent.com/11056766/101188245-bdd67280-3655-11eb-8b42-18a189a00c9c.png)

**Comment by gingerbeardman** [comment]
Looks good, I shall await the new build.
