### ISSUE TITLE
# of App Store Apps Indicator Feature Request

### ISSUE THREAD

**Issue by big610** [mangerlahn/Latest#61]
Max, While your working on 6.2, as 6.1 is still crashing. I had another Feature Request; an indicator/asterisk/icon to show which apps are from the App Store. I mentioned earlier giving us a Number count on Installed Updates Total Apps up to date, if you split both Available Updates & Installed Updates, giving App Store & Non Apps Store # counts for both categories. 
You mentioned ability to sort, I suggest categories to sort by App Store, Sparkle, Alphabetical, Date; and mentioned earlier Save As to text/clipboard.
I also like the idea to have Latest sit in the Menu Bar, with your icon colored & a # indicator of updates, and for those that don't want Menu Bar Preferences to adjust to personal choice.

**Comment by mangerlahn** [comment]
I very much like this one! The things you mentioned are part of #31, #63, #64 and #58, so I will close this issue.
