### ISSUE TITLE
Latest dies immediatly after starting

### ISSUE THREAD

**Issue by BenediktS1** [mangerlahn/Latest#62]
Hello Max.

After starting Latest 0.6.1 its main screen is visble for approx. 0.1 s and its gone.

In console I found this message:

`Sep 27 14:56:42 orion com.apple.xpc.launchd[1] (com.max-langer.Latest.117228[3117]): Service exited due to SIGILL | sent by exc handler[3117]`

I've the latest version of Mac OS X 10.14.6 (18G103).

Any idea?

Best regards,
Benedikt

**Comment by mangerlahn** [comment]
I changed the update checking mechanism. This might fix this problem. Could you try this "beta" and see if it works?
https://max.codes/latest/Latest_0.6.2_Beta.zip

**Comment by BenediktS1** [comment]
Thank you. The crash is gone.
