### ISSUE TITLE
Reenable Mac App Store updates

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#65]
I'm not sure what this icon means? 

- No tooltip when hovering over it
- Nothing in Console log either

![Screen shot 2019-10-07 at 12 01 16](https://user-images.githubusercontent.com/49612/66306836-a0473500-e8fa-11e9-8cc0-3f2c63411393.png)

Both these apps are from the Mac App Store, but there are no updates waiting there for them. However when I went to their respective MAS pages, they were shown as downloadable. So their updates were not being tracked by the MAS. Maybe I had switched to direct downloads for both of them? Not sure. 

Anyway, I have downloaded both again from the MAS and will see if this issue happens again.

**Comment by mangerlahn** [comment]
I can reproduce this on my side. I can't update any Mac App Store apps under 10.15. I need to further investigate this.

**Comment by gingerbeardman** [comment]
BTW I'm on 10.14.6

**Comment by mangerlahn** [comment]
It seems that the underlying framework used for updating apps does not work anymore. There are new frameworks, but I have to adapt to them. I will disable update support for Mac App Store apps in 0.6.2 and reenable this in a later update.

mas-cli has the same problems apparently https://github.com/mas-cli/mas/issues.

**Comment by mangerlahn** [comment]
Just for documentation, there are private frameworks called `AppStoreFoundation` and `AppStoreKit` who seem to replace the existing `CommerceKit` and `StoreFoundation`, which are still present but appear to not be working anymore.. 
I will attempt to see how they are working and seek to integrate them in the next bigger release.

**Comment by mangerlahn** [comment]
So I spend a couple of days with that. Apple significantly upgraded the access control on this stuff. The `AppStoreFoundation` delegates all calls to a process called `appstoreagent`, which checks the senders entitlements. That way Apple ensures that only processes can access update information that are intended to. I can't set these entitlements without disabling System Integrity Protection.

**Comment by mangerlahn** [comment]
I just realized that mas was able to re-enable update support for newer OSes, so I was able to do so as well :)

**Comment by rgoldberg** [comment]
> So I spend a couple of days with that. Apple significantly upgraded the access control on this stuff. The `AppStoreFoundation` delegates all calls to a process called `appstoreagent`, which checks the senders entitlements before it returns anything useful. That way Apple ensures that only processes can access update information that are intended to. I can't set these entitlements without disabling System Integrity Protection.
> 
> I currently have no idea how to continue with this, maybe someone here has a deeper understanding of how all that permission and entitlements stuff works and how we could build a system that can access the update information.
> 
> One idea that probably don't work: Building a small helper app that is unsigned but has the entitlements required.

@mangerlahn Hi, I'm the current primary developer of mas. I'm trying to improve how mas determines that MAS apps are outdated & how it installs updates from the MAS.

I know that your quoted commented was from over 5 years ago, but have you ever learned how such entitlements work?

I haven't yet had to deal with them, and I'm not knowledgeable about macOS interprocess communication.

Do you remember what functions & types were used from any of your investigations?

Thanks for any potential help.
