### ISSUE TITLE
Make circular progress go away once complete 

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#66]
Seems needless to be there after it is complete?

![Screen shot 2019-10-20 at 16 48 19](https://user-images.githubusercontent.com/49612/67162988-c096db00-f361-11e9-9feb-7f4914dd3207.png)

**Comment by mangerlahn** [comment]
Does this happen only in the beta I gave you?

**Comment by gingerbeardman** [comment]
Hmm. I'll check again but I left it a while. 

If that's the case then progress needs to be reported in a better way if I am still needing to wait.

**Comment by gingerbeardman** [comment]
So it does eventually disappear. I timed it at exactly(?) 30 seconds.

Console.app output:
https://gist.github.com/gingerbeardman/6775fb8cafeecf09a4d23d4919a9878d

**Comment by gingerbeardman** [comment]
Are you in control of the timeout?
