### ISSUE TITLE
Updated app stayed visible until I manually clicked refresh arrow

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#67]
Using 0.6.2

I updated CodeKit app and the update completed but the app stayed in the list and the update button reappeared and latest did another progress scan.

When I manually clicked the refresh arrow, the app disappeared from the list.

**Comment by mangerlahn** [comment]
This should be fixed with 117a03f4f480373ad3de237bfcc89c2c592bc13f as well.
