### ISSUE TITLE
Crash when any letter is typed into search field, or content is pasted into search

### ISSUE THREAD

**Issue by sebj** [mangerlahn/Latest#68]
When I type any letter into the search field, or paste any text content into the search field, Latest immediately crashes.

Able to reproduce every time on my machine, with 26 apps under the "Installed Apps" section (mix of App Store & Sparkle) and 1 App Store app under "Available Updates".

Looking in Console, the crash logs all list the same reason: the main thread crashed `due to uncaught exception 'NSTableViewException', reason: 'NSTableView error inserting/removing/moving row 0 (numberOfRows: 0).'` (where I've observed 0 to be 1, 2, 6, 10, etc. depending on the letter I tried to type, and where the row number always matches the number of rows in the message).

I've attached a zip containing 6 of these crash log reports. [Latest Search Crash Logs.zip](https://github.com/mangerlahn/Latest/files/3797730/Latest.Search.Crash.Logs.zip)

Environment:
* Latest version 0.6.2 (357)
* macOS Catalina 10.15.1 (19B88)

**Comment by gingerbeardman** [comment]
I can also reproduce.

**Comment by mangerlahn** [comment]
Ooops, that slipped through with 0.6.2. Sorry about that, fix incoming ;)

**Comment by sebj** [comment]
Thanks! :)
