### ISSUE TITLE
Provide ready to use Build

### ISSUE THREAD

**Issue by mangerlahn** [mangerlahn/Latest#7]
Currently tech-savvy people can compile and run Latest. But EE may not know how to do that. 

The following steps need to be done:
 

- [x] Latest should be provided as a compiled ready to use app for easier installation.

- [x] Sparkle should be included into the App to enable easy updating to future versions 

- [x] A simple one page showing the apps features and a download button.

**Comment by manniL** [comment]
Maybe it'd be useful to let TravisCI compile Latest on every push to master 🤔

**Comment by mangerlahn** [comment]
It seems to be not that easy, since the build is linked to the Sparkle feed to notify users about an update. That may be solvable through some hook or so.. But these steps require signing with multiple private keys, so I guess this will be a manual step on my side 🙃
