### ISSUE TITLE
Apple Icon showing App Store Apps 

### ISSUE THREAD

**Issue by big610** [mangerlahn/Latest#70]
Apple Icon showing App Store Apps, Feature Request.
Will assist tremendously knowing the differences. Some apps are both Web Version & App Store.
When you add the sorting ability, sort: by App Store, by non-App Store.

**Comment by mangerlahn** [comment]
This will be done with #31.

**Comment by mangerlahn** [comment]
<img width="538" alt="Bildschirmfoto 2020-04-18 um 18 03 51" src="https://user-images.githubusercontent.com/11056766/79642694-60adaf80-819f-11ea-9896-ba7153c6fca7.png">
Fixed with 01b995e7c21555c7f15139752d0da21609b9e776.
