### ISSUE TITLE
Problem with the number version of WireGuard downloaded from the AppStore.

### ISSUE THREAD

**Issue by Wielosmakowy** [mangerlahn/Latest#71]
After downloading from the AppStore, "Latest" shows a version, e.g., 1.0.8, but in macOS installed is version 0.0.20191105. The program shows the outdated version (0.0.20191105) and offers an upgrade to version 1.0.8, which is 0.0.20191105.

**Comment by mangerlahn** [comment]
I currently do the update checking independently from the Mac App Store. This mismatches in some cases, like WireGuard. I plan to use the Mac App Store implementation if I get #65 to work.

**Comment by Wielosmakowy** [comment]
There is a similar in the latest version of the Safari plugin. -  Tampermonkey (6108). While the authors changed the way of marking the version from X.Y.Z (X - Major Version, Y - Minor version, Z - Build) to Z, "Latest" reports that we have an outdated version.
Now or we have to wait for the next version and see if it is the authors' mistake and one-time change, or intentional and definitive change.

**Comment by mangerlahn** [comment]
Duplicate of #65
