### ISSUE TITLE
Include apps in user application folder

### ISSUE THREAD

**Issue by anpenzel** [mangerlahn/Latest#72]
I keep most of my apps in the users's own application folder (~user/Applications) - just not to clutter the system for all other users.

Unfortunately 'latest' does not seem to include this folder?! It only shows information about apps saved in /Application. Is there an easy way to overcome this limitation - or is it a feature request?

Thanks for this helpful app!
Greetings, Andreas

**Comment by gingerbeardman** [comment]
Good idea.

@mangerlahn with the speedups from  #48 it should be possible to scan the whole of the main drive for apps with no worry about performance issues?

**Comment by mangerlahn** [comment]
Sure!
@gingerbeardman you are correct, there is no performance issue with implementing this. The system returns _all_ apps on the system, I currently filter for the ones in `/Applications`. 

This is more of an discussion about where to look. IIRC apps can't be updated if they are located in the downloads folder. We should not include apps from there if that is the case. 
But `~/Applications` seems fine. I guess it is sufficient to add this and extend the list of "permitted" folders on demand.

**Comment by mangerlahn** [comment]
Fixed with 347e384
