### ISSUE TITLE
Quit Latest immediately when closing the Window

### ISSUE THREAD

**Issue by big610** [mangerlahn/Latest#74]
Close with Red X:
When you attempt to close Latest from the Desktop, from the upper left corner, Left Click Red X, it still appears in the bottom dock, you must enable two moves, right click, Quit.

Could you please look to get Latest to completely close from the Desktop, with one simple move, Left Click the Red X.

In the future enabling Latest from the Menu Bar to always run, you still would want to close the Desktop with, Left Click the Red X.
You also will also want to enable Latest/Preferences from Grey/Inactive when you add features in the Preferences spot.

Upper Right Corner Six Squares Button:
When you select an app, the right slide opens up; 
Please enact the Six Squares Button to close the right slide, when its open.

**Comment by mangerlahn** [comment]
I added #77 as a separate issue.
