### ISSUE TITLE
VST/AU Plugin Support?

### ISSUE THREAD

**Issue by samaero** [mangerlahn/Latest#79]
Thank you for your work on this - it's a really useful & well-designed app!

I'm a computer musician, and have a lot of VST / Audiounit / AAX plugins. These are notoriously hard to keep up to date because of all the different third party plugin makers. I wanted to know if you'd be interested in trying to support these formats in Latest? Not sure how involved it would be, but I'm happy to beta test if you do decide to try it.

**Comment by mangerlahn** [comment]
Thank you for bringing this up! While I'd love to support more apps (and plugins in general), adding and maintaining these sources would be a huge time-consuming task. Something I just can't handle in my spare time. I really wish I could give you a better answer on this.

**Comment by mangerlahn** [comment]
There is another app that does update checks on Mac software. It is called MacUpdater (https://www.corecode.io/macupdater/index.html). AFAIK it does its update checks with a server-based approach, supporting far more apps (and plugins in general, again). Checking only is also free, if that is sufficient for you.

**Comment by samaero** [comment]
Thanks for letting me know! I like the design & layout of Latest a lot better, but it does seem like MacUpdater would catch more of the updates I'm looking for. Thank you!
