### ISSUE TITLE
Latest misses the application Reveal.app

### ISSUE THREAD

**Issue by sleifer** [mangerlahn/Latest#85]
Reveal uses Sparkle, but is not listed by Latest. This looks to be because the `SUFeedURL` in Reveal is quoted.

Proposed fix is to trim any quotes from the feed url after reading in the `SparkleCheckerOperation` constructor.

I can create a pull request if you wish.

**Comment by mangerlahn** [comment]
Sure! :) 
Feel free to put both issues into PR one if you like!
