### ISSUE TITLE
Not showing chrome and Spotify

### ISSUE THREAD

**Issue by Rishikleo** [mangerlahn/Latest#87]
I'm using the latest version of the "latest" app(pun intended)
I'm unable to see some apps mainly chrome, Spotify
Any fix????

![Uploading Screenshot 2020-06-19 at 9.48.56 PM.png…]()
![image](https://user-images.githubusercontent.com/61243891/85155741-c4735800-b276-11ea-8ed2-38894028080a.png)

**Comment by mangerlahn** [comment]
I am going to address this in #95 :)
