### ISSUE TITLE
App Does Not Maximize from Dock

### ISSUE THREAD

**Issue by doctopus** [mangerlahn/Latest#88]
Once the app is minimized, it does not maximize upon clicking the app icon in the dock. 

Currently the only way to bring the app to front is right clicking the dock icon and selecting the window.

This behavior was seen in Mac Catalina 10.15.6

It should be possible to bring the app to maximize by clicking the dock icon.

**Comment by mangerlahn** [comment]
Good catch, thank you! This will be fixed in the next update :)
