### ISSUE TITLE
Latest doesn't show all apps

### ISSUE THREAD

**Issue by 12-Seconds** [mangerlahn/Latest#90]
Out of my 90+ apps, only about 12 show up in Installed Apps. Is Latest supposed to detect apps automatically, or is there a list of supported apps, which helps it check for updates for those apps?

**Comment by fitchecks-evan** [comment]
This is probably why: "Latest currently supports apps downloaded from the Mac App Store and apps that use Sparkle for updates"
Some of my apps installed outside of the app store don't use Sparkle, could be the same with yours. You can see which of your installed apps use the Sparkle framework like so:
`find /Applications -name Sparkle.framework | awk -F'/' '{print $3}' | awk -F'.' '{print $1}'find /Applications -name Sparkle.framework | awk -F'/' '{print $3}' | awk -F'.' '{print $1}'`

**Comment by 12-Seconds** [comment]
@fitchecks-evan I get the following when running the above command:
```
awk: warning: command line argument `/Applications' is a directory: skipped
awk: fatal: cannot open file `-name' for reading: No such file or directory
```

**Comment by Gummibando** [comment]
@12-Seconds 

This works for me:
`find /Applications -name Sparkle.framework | awk -F'/' '{print $3}'`

Also, Sparkle's lesser known cousin:
`find /Applications -name GitHubUpdates.framework | awk -F'/' '{print $3}'`
