### ISSUE TITLE
Does Latest support checking for self-updates?

### ISSUE THREAD

**Issue by liby** [mangerlahn/Latest#93]
When I open the Latest, I see a prompt to automatically detect updates.

![image](https://user-images.githubusercontent.com/38807139/98896657-77717600-24e4-11eb-8786-76f74fa4ca59.png)

So is it possible for it to detect its own updates and display them in the Available Updates list?

It's because I don't like in-app updates that I want to find a software that manages app updates uniformly.

It would be better if the Latest can detect and display its own updates, rather than just through `brew` or in-program updates.

**Comment by mangerlahn** [comment]
Well Latest checks itself for updates and it also appears in the update list, but it does not update itself. I should improve on that.

![Bildschirmfoto 2020-11-19 um 22 00 07](https://user-images.githubusercontent.com/11056766/99723527-98246780-2ab2-11eb-8c50-b5c274bf3758.png)

**Comment by foss-** [comment]
Just updated to 0.7 (434) via "Available Updates". Has this been fixed already?

**Comment by liby** [comment]
This feature has been added in the latest version.

@mangerlahn 
By the way, has the `Update Al`" button been removed? At the moment I can only find it in `File/Update All`
