### ISSUE TITLE
Prevent incompatible updates from installing

### ISSUE THREAD

**Issue by big610** [mangerlahn/Latest#94]
Hello Max:
Big Sur App Banner.
This application requires macOS 11.0 or later. You can't use this version of the application with this version of macOS.

[You can't use this version of the application.pdf](https://github.com/mangerlahn/Latest/files/5561972/You.can.t.use.this.version.of.the.application.pdf)

Can the Sparkle code read this message internally, can it read anything to this regard? 
I believe it will be possible after looking at MacUpdater compatibility knowing 11.0 apps.

I suggest a New Category named "Available macos 11.0 or later Updates".
Where you can manually move it into this Category &/ or out. 
Ignore Apps:
https://github.com/mangerlahn/Latest/issues/49

**Comment by mangerlahn** [comment]
Ouch! I am sorry Latest installed an update that is not supported on your system. I hope you were able to redownload an old version of that app, or restored it from Time Machine.

I need to disable updates for incompatible apps, thank you for mentioning!

**Comment by big610** [comment]
Max,
No apology needed, everything you do is a bonus. Let me be more specific, Version 0.6.3 (370), macOS 10.15.7. I never let the app update internally, I prefer to get myself, download, & always save a copy. I suppose if used the Update button, it could put a 11.0 app on 10.15.7. Looking at MacUpdater, it shows me the new 11.0 Version #, but stays in Green saying not Outdated. So you should be able to code a new Latest Big Sur Compatiblity. I'm also looking at the 11.0 app in Latest, & others, very few are reading the Sparkle Compatibility, can you get Sparkle to read Compatibility? App Store has the Compatibility, so Sparkle should read? Which macOS are you on, and if not when your going to Big Sur? When you update next please see if you can add my Enhancement suggestion: https://github.com/mangerlahn/Latest/issues/74

**Comment by mangerlahn** [comment]
Resolved with 1d8635b
