### ISSUE TITLE
Show Unsupported Apps

### ISSUE THREAD

**Issue by mangerlahn** [mangerlahn/Latest#95]
Latest currently only lists apps it knows how to update. 
This confuses a lot of users since it seems like it does not find the other apps. Therefore they should be displayed, probably grayed out or with an explanation that they can't be checked for an update.

**Comment by mangerlahn** [comment]
Fixed with 3dfb9c8

**Comment by mhdhejazi** [comment]
I guess a more intuitive way would be having three sections in the sidebar:

- Update is available
- Up to date
- Unspecified/Others

With those sections, there is no need for the menu item options. And the last section can be collapsed by default.
