### ISSUE TITLE
Latest 0.6.3 crashes on Big Sur

### ISSUE THREAD

**Issue by Gummibando** [mangerlahn/Latest#98]
In macOS Bug Sur (11.0.1), Latest 0.6.3 consistently crashes after every app update using Sparkle if I initiate the update in Latest.

[Latest Crash Report.txt.zip](https://github.com/mangerlahn/Latest/files/5625988/Latest.Crash.Report.txt.zip)

**Comment by mangerlahn** [comment]
Attempted to fix in 3958c12, if the issue persists in v0.7, we should reopen this one :)
